// Generated by `statex calls sync`. Do not edit.
//! Typed clients of other statex apps' actors.
//!
//! In a component these call the callee through the host. In native
//! `cargo test` they call the stub installed with `<actor type>::stub(..)`
//! (per test thread); a call without a stub panics.
#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

mod bindings_statex_queue {
    wit_bindgen::generate!({
        path: "wit",
        world: "statex:queue/statex-calls",
        with: { "statex:host/actors@0.1.0": statex_guest::actors },
        additional_derives: [PartialEq],
    });
}

pub mod statex {
    /// Actors of app `queue`.
    pub mod queue {
        pub mod queue {
            use super::super::super::bindings_statex_queue::statex::queue::queue as raw;
            pub use raw::{Config, Input, Outcome, Status};
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{configure, send, send_batch, settle, pause, resume, info};

            /// Test double for `queue` actors of app `queue`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Queue {
                fn configure(&self, actor: &str, configuration: &Config) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    panic!("queue queue.configure was called without a stub; implement it in the `Queue` stub")
                }
                fn send(&self, actor: &str, id: &str, body: &[u8], delay_ms: u64) -> Result<Result<bool, String>, statex_guest::actors::CallError> {
                    panic!("queue queue.send was called without a stub; implement it in the `Queue` stub")
                }
                fn send_batch(&self, actor: &str, messages: &[Input]) -> Result<Result<Vec<bool>, String>, statex_guest::actors::CallError> {
                    panic!("queue queue.send-batch was called without a stub; implement it in the `Queue` stub")
                }
                fn settle(&self, actor: &str, token: &str, outcomes: &[Outcome]) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    panic!("queue queue.settle was called without a stub; implement it in the `Queue` stub")
                }
                fn pause(&self, actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    panic!("queue queue.pause was called without a stub; implement it in the `Queue` stub")
                }
                fn resume(&self, actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    panic!("queue queue.resume was called without a stub; implement it in the `Queue` stub")
                }
                fn info(&self, actor: &str) -> Result<Status, statex_guest::actors::CallError> {
                    panic!("queue queue.info was called without a stub; implement it in the `Queue` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Queue>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Queue + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Queue> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("queue queue was called without a stub; call statex_calls::statex::queue::queue::stub(..) first")
                    })
                }

                pub fn configure(actor: &str, configuration: &Config) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    current().configure(actor, configuration)
                }

                pub fn send(actor: &str, id: &str, body: &[u8], delay_ms: u64) -> Result<Result<bool, String>, statex_guest::actors::CallError> {
                    current().send(actor, id, body, delay_ms)
                }

                pub fn send_batch(actor: &str, messages: &[Input]) -> Result<Result<Vec<bool>, String>, statex_guest::actors::CallError> {
                    current().send_batch(actor, messages)
                }

                pub fn settle(actor: &str, token: &str, outcomes: &[Outcome]) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    current().settle(actor, token, outcomes)
                }

                pub fn pause(actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    current().pause(actor)
                }

                pub fn resume(actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    current().resume(actor)
                }

                pub fn info(actor: &str) -> Result<Status, statex_guest::actors::CallError> {
                    current().info(actor)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, &Config) -> Result<Result<(), String>, statex_guest::actors::CallError> = raw::configure;
                    let _: fn(&str, &str, &[u8], u64) -> Result<Result<bool, String>, statex_guest::actors::CallError> = raw::send;
                    let _: fn(&str, &[Input]) -> Result<Result<Vec<bool>, String>, statex_guest::actors::CallError> = raw::send_batch;
                    let _: fn(&str, &str, &[Outcome]) -> Result<Result<(), String>, statex_guest::actors::CallError> = raw::settle;
                    let _: fn(&str) -> Result<(), statex_guest::actors::CallError> = raw::pause;
                    let _: fn(&str) -> Result<(), statex_guest::actors::CallError> = raw::resume;
                    let _: fn(&str) -> Result<Status, statex_guest::actors::CallError> = raw::info;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
        pub mod worker {
            use super::super::super::bindings_statex_queue::statex::queue::worker as raw;
            pub use raw::{Delivery};
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{process};

            /// Test double for `worker` actors of app `queue`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Worker {
                fn process(&self, actor: &str, queue_key: &str, token: &str, messages: &[Delivery]) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    panic!("queue worker.process was called without a stub; implement it in the `Worker` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Worker>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Worker + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Worker> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("queue worker was called without a stub; call statex_calls::statex::queue::worker::stub(..) first")
                    })
                }

                pub fn process(actor: &str, queue_key: &str, token: &str, messages: &[Delivery]) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    current().process(actor, queue_key, token, messages)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, &str, &str, &[Delivery]) -> Result<Result<(), String>, statex_guest::actors::CallError> = raw::process;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
        pub mod sink {
            use super::super::super::bindings_statex_queue::statex::queue::sink as raw;
            pub use raw::{Entry};
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{record, entries};

            /// Test double for `sink` actors of app `queue`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Sink {
                fn record(&self, actor: &str, id: &str, body: &[u8]) -> Result<Result<bool, String>, statex_guest::actors::CallError> {
                    panic!("queue sink.record was called without a stub; implement it in the `Sink` stub")
                }
                fn entries(&self, actor: &str) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    panic!("queue sink.entries was called without a stub; implement it in the `Sink` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Sink>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Sink + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Sink> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("queue sink was called without a stub; call statex_calls::statex::queue::sink::stub(..) first")
                    })
                }

                pub fn record(actor: &str, id: &str, body: &[u8]) -> Result<Result<bool, String>, statex_guest::actors::CallError> {
                    current().record(actor, id, body)
                }

                pub fn entries(actor: &str) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    current().entries(actor)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, &str, &[u8]) -> Result<Result<bool, String>, statex_guest::actors::CallError> = raw::record;
                    let _: fn(&str) -> Result<Vec<Entry>, statex_guest::actors::CallError> = raw::entries;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
    }
}
