//! `statex calls`: typed clients for calling other actors from inside an actor.
//!
//! For every callee app listed under `[calls] apps` in statex.toml, `sync`
//! writes `wit/deps/<ns>--<name>/client.wit`: package `<ns>:<name>` (see
//! [`client_package`]) with one interface per actor type. Each method takes the
//! callee's key first and returns `result<T, call-error>`. Rust projects also
//! get `src/statex_calls.rs`, which exposes the same functions with stub
//! traits for native `cargo test`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use statex_runtime::{client_package, validate_app_name, ActorType, Ty};

use crate::project::{source_surface, Project};
use crate::workspace::Workspace;

const HEADER: &str = "Generated by `statex calls sync`";
const HOST_ACTORS: &str = "statex:host/actors@0.1.0";
const WORLD: &str = "statex-calls";
pub const SHIM: &str = "src/statex_calls.rs";

fn client_file(app: &str) -> PathBuf {
    let (ns, name) = client_package(app);
    PathBuf::from(format!("wit/deps/{ns}--{name}/client.wit"))
}

/// A callee app and its actor types.
pub struct Callee {
    pub app: String,
    pub types: Vec<ActorType>,
}

/// Apps listed under `[calls] apps`, validated and deduplicated.
pub fn listed(p: &Project) -> Result<Vec<String>> {
    let mut out: Vec<String> = Vec::new();
    for a in &p.cfg.calls.apps {
        validate_app_name(a).with_context(|| format!("[calls] apps in statex.toml: {a:?}"))?;
        if !out.contains(a) {
            out.push(a.clone());
        }
    }
    Ok(out)
}

/// Source directory of callee `app`: the project itself, `[calls] paths`,
/// or a workspace app. `None` if the app's source is not available locally.
pub fn callee_root(p: &Project, ws: Option<&Workspace>, app: &str) -> Result<Option<PathBuf>> {
    if app == p.app() {
        return Ok(Some(p.root.clone()));
    }
    if let Some(d) = p.cfg.calls.paths.get(app) {
        let root = p.root.join(d);
        if !root.join("statex.toml").is_file() {
            bail!("[calls] paths: {} has no statex.toml for app {app}", root.display());
        }
        let callee = Project::find(&root)?;
        if callee.app() != app {
            bail!("[calls] paths: app {app:?} points to {} whose manifest names {:?}", root.display(), callee.app());
        }
        return Ok(Some(callee.root));
    }
    let Some(ws) = ws else { return Ok(None) };
    Ok(ws.projects()?.into_iter().find(|p| p.app() == app).map(|p| p.root))
}

/// The actor types of `app` read from source (see [`callee_root`]).
pub fn local_types(p: &Project, ws: Option<&Workspace>, app: &str) -> Option<Result<Vec<ActorType>>> {
    let root = match callee_root(p, ws, app) {
        Ok(Some(root)) => root,
        Ok(None) => return None,
        Err(e) => return Some(Err(e)),
    };
    let mut r = source_surface(&root).map(|s| s.0);
    if r.is_err() && app == p.app() {
        // Calls within the app: its world may import its own client package
        // before that has been generated.
        r = r.or_else(|e| exported_types(&root.join("wit")).map_err(|_| e));
    }
    Some(r.with_context(|| format!("read app {app} at {}", root.display())))
}

/// Exported actor types of a WIT directory, ignoring client imports (which
/// may not have been generated yet).
fn exported_types(wit: &Path) -> Result<Vec<ActorType>> {
    let dir = tempfile::tempdir()?;
    copy_dir(wit, dir.path())?;
    for e in std::fs::read_dir(dir.path())? {
        let path = e?.path();
        if path.extension().is_some_and(|x| x == "wit") {
            let text = std::fs::read_to_string(&path)?;
            let kept: Vec<&str> = text.lines().filter(|l| !is_client_import(l)).collect();
            std::fs::write(&path, kept.join("\n"))?;
        }
    }
    Ok(statex_runtime::inspect_wit(dir.path(), None)?.types)
}

fn is_client_import(line: &str) -> bool {
    let Some(rest) = line.trim().strip_prefix("import ") else { return false };
    let Some((pkg, _)) = rest.split_once('/') else { return false };
    let Some((ns, name)) = pkg.split_once(':') else { return false };
    statex_runtime::app_of_package(ns, name).is_some()
}

fn copy_dir(from: &Path, to: &Path) -> Result<()> {
    std::fs::create_dir_all(to)?;
    for e in std::fs::read_dir(from)? {
        let e = e?;
        let target = to.join(e.file_name());
        if std::fs::metadata(e.path())?.is_dir() {
            copy_dir(&e.path(), &target)?;
        } else {
            std::fs::copy(e.path(), &target)?;
        }
    }
    Ok(())
}

/// The files `sync` writes, relative to the project root.
pub fn render(p: &Project, callees: &[Callee]) -> Result<BTreeMap<PathBuf, String>> {
    let mut out = BTreeMap::new();
    for c in callees {
        out.insert(client_file(&c.app), client_wit(c)?);
    }
    if is_rust(p) && !callees.is_empty() {
        out.insert(PathBuf::from(SHIM), rust_shim(callees)?);
    }
    Ok(out)
}

pub fn is_rust(p: &Project) -> bool {
    p.cfg.build.is_none()
}

/// Generated files on disk (ours, recognized by their header).
pub fn on_disk(p: &Project) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();
    let mut add = |rel: PathBuf| {
        if let Ok(s) = std::fs::read_to_string(p.root.join(&rel)) {
            if s.lines().next().is_some_and(|l| l.contains(HEADER)) {
                out.insert(rel, s);
            }
        }
    };
    for e in std::fs::read_dir(p.root.join("wit/deps")).into_iter().flatten().flatten() {
        add(Path::new("wit/deps").join(e.file_name()).join("client.wit"));
    }
    add(PathBuf::from(SHIM));
    out
}

/// Differences between the generated files and what is on disk.
pub fn diff(want: &BTreeMap<PathBuf, String>, have: &BTreeMap<PathBuf, String>) -> Vec<String> {
    let mut out = Vec::new();
    for (k, v) in want {
        match have.get(k) {
            None => out.push(format!("missing {}", k.display())),
            Some(h) if h != v => out.push(format!("out of date: {}", k.display())),
            _ => {}
        }
    }
    for k in have.keys().filter(|k| !want.contains_key(*k)) {
        out.push(format!("stale: {}", k.display()));
    }
    out
}

/// Writes `want`, removes generated files no longer wanted, and makes the
/// host WIT available. Returns the changed paths.
pub fn write(p: &Project, ws: Option<&Workspace>, want: &BTreeMap<PathBuf, String>) -> Result<Vec<String>> {
    let have = on_disk(p);
    let mut changed = Vec::new();
    for (rel, text) in want {
        if have.get(rel) == Some(text) {
            continue;
        }
        let path = p.root.join(rel);
        if path.exists() && !have.contains_key(rel) {
            bail!("{} exists and was not generated by statex; move it away first", rel.display());
        }
        std::fs::create_dir_all(path.parent().unwrap())?;
        std::fs::write(&path, text).with_context(|| format!("write {}", path.display()))?;
        changed.push(rel.display().to_string());
    }
    for rel in have.keys().filter(|k| !want.contains_key(*k)) {
        let path = p.root.join(rel);
        std::fs::remove_file(&path)?;
        if rel.starts_with("wit/deps") {
            let dir = path.parent().unwrap();
            if std::fs::read_dir(dir)?.next().is_none() {
                std::fs::remove_dir(dir)?;
            }
        }
        changed.push(format!("{} (removed)", rel.display()));
    }
    if !want.is_empty() && crate::scaffold::ensure_host_wit(&p.root, ws)? {
        changed.push("wit/deps/statex-host".into());
    }
    Ok(changed)
}

/// The generated files, with callees read from local source where available
/// (the project itself or workspace apps) and the existing client WIT of the
/// others kept as is. Also returns the apps that are not available locally.
pub fn local_plan(p: &Project, ws: Option<&Workspace>) -> Result<(BTreeMap<PathBuf, String>, Vec<String>)> {
    let apps = listed(p)?;
    let have = on_disk(p);
    let mut callees = Vec::new();
    let mut keep = BTreeMap::new();
    let mut remote = Vec::new();
    for app in &apps {
        match local_types(p, ws, app) {
            Some(types) => callees.push(Callee { app: app.clone(), types: types? }),
            None => {
                let rel = client_file(app);
                match have.get(&rel) {
                    Some(text) => {
                        let parsed = parse_client(&rel, text)?;
                        if parsed.app != *app {
                            bail!("client interface for app {app} names {}; run `statex calls sync --from-url <node url>`", parsed.app);
                        }
                        keep.insert(rel, text.clone());
                    }
                    None => bail!("no client interface for app {app}: configure [calls] paths for its source, or run `statex calls sync --from-url <node url>`"),
                }
                remote.push(app.clone());
            }
        }
    }
    // The shim is regenerated from kept client WIT so it covers every callee.
    for (rel, text) in &keep {
        callees.push(parse_client(rel, text)?);
    }
    let mut want = render(p, &callees)?;
    want.extend(keep);
    Ok((want, remote))
}

/// Regenerates client files from local sources (see [`local_plan`]). Used
/// before builds so client interfaces follow local edits.
pub fn sync_local(p: &Project, ws: Option<&Workspace>) -> Result<Vec<String>> {
    if p.cfg.calls.apps.is_empty() && on_disk(p).is_empty() {
        return Ok(vec![]);
    }
    let (want, _) = local_plan(p, ws)?;
    write(p, ws, &want)
}

/// Reads a generated client WIT back into the callee's actor types (as the
/// caller sees them; enough to regenerate the Rust shim).
fn parse_client(rel: &Path, text: &str) -> Result<Callee> {
    let dir = tempfile::tempdir()?;
    std::fs::create_dir_all(dir.path().join("deps/statex-host"))?;
    std::fs::write(dir.path().join("deps/statex-host/statex-host.wit"), crate::scaffold::HOST_WIT)?;
    std::fs::write(dir.path().join("client.wit"), text)?;
    let calls = statex_runtime::inspect_wit_calls(dir.path(), Some(WORLD)).with_context(|| format!("parse {}", rel.display()))?;
    let app = calls.first().map(|c| c.app.clone()).with_context(|| format!("{}: no interfaces", rel.display()))?;
    let types = calls
        .into_iter()
        .map(|c| ActorType { name: c.actor_type, export: c.import, docs: None, methods: c.methods, alarm: None })
        .collect();
    Ok(Callee { app, types })
}

// ---------- WIT ----------

const WIT_KEYWORDS: &[&str] = &[
    "use", "type", "func", "u8", "u16", "u32", "u64", "s8", "s16", "s32", "s64", "f32", "f64", "float32", "float64",
    "char", "record", "resource", "own", "borrow", "flags", "variant", "enum", "bool", "string", "option", "result",
    "future", "stream", "error-context", "list", "as", "from", "static", "interface", "tuple", "import", "export",
    "world", "package", "constructor", "include", "with", "async", "_",
];

pub(crate) fn is_wit_id(s: &str) -> bool {
    !s.is_empty()
        && s.split('-').all(|seg| {
            seg.chars().next().is_some_and(|c| c.is_ascii_lowercase())
                && seg.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        })
}

pub(crate) fn wid(s: &str) -> String {
    if WIT_KEYWORDS.contains(&s) {
        format!("%{s}")
    } else {
        s.to_string()
    }
}

fn wit_ty(t: &Ty) -> String {
    match t {
        Ty::Bool => "bool".into(),
        Ty::U8 => "u8".into(),
        Ty::U16 => "u16".into(),
        Ty::U32 => "u32".into(),
        Ty::U64 => "u64".into(),
        Ty::S8 => "s8".into(),
        Ty::S16 => "s16".into(),
        Ty::S32 => "s32".into(),
        Ty::S64 => "s64".into(),
        Ty::F32 => "f32".into(),
        Ty::F64 => "f64".into(),
        Ty::Char => "char".into(),
        Ty::String => "string".into(),
        Ty::List { element } => format!("list<{}>", wit_ty(element)),
        Ty::Option { inner } => format!("option<{}>", wit_ty(inner)),
        Ty::Result { ok, err } => match (ok, err) {
            (None, None) => "result".into(),
            (Some(o), None) => format!("result<{}>", wit_ty(o)),
            (o, Some(e)) => format!(
                "result<{}, {}>",
                o.as_deref().map_or("_".into(), wit_ty),
                wit_ty(e)
            ),
        },
        Ty::Tuple { items } => {
            format!("tuple<{}>", items.iter().map(wit_ty).collect::<Vec<_>>().join(", "))
        }
        Ty::Record { name, .. } | Ty::Variant { name, .. } | Ty::Enum { name, .. } | Ty::Flags { name, .. } => wid(name),
    }
}

fn named(t: &Ty) -> Option<&str> {
    match t {
        Ty::Record { name, .. } | Ty::Variant { name, .. } | Ty::Enum { name, .. } | Ty::Flags { name, .. } => Some(name),
        _ => None,
    }
}

fn children(t: &Ty) -> Vec<&Ty> {
    match t {
        Ty::List { element } => vec![element],
        Ty::Option { inner } => vec![inner],
        Ty::Result { ok, err } => ok.iter().chain(err.iter()).map(|b| &**b).collect(),
        Ty::Tuple { items } => items.iter().collect(),
        Ty::Record { fields, .. } => fields.iter().map(|f| &f.ty).collect(),
        Ty::Variant { cases, .. } => cases.iter().filter_map(|c| c.ty.as_ref()).collect(),
        _ => vec![],
    }
}

/// Named types reachable from `t`, dependencies first.
fn collect<'a>(t: &'a Ty, out: &mut Vec<&'a Ty>, ctx: &str) -> Result<()> {
    for c in children(t) {
        collect(c, out, ctx)?;
    }
    if let Some(n) = named(t) {
        match out.iter().find(|x| named(x) == Some(n)) {
            Some(x) if *x != t => bail!("{ctx}: two different types are named `{n}`; client interfaces need unique type names"),
            Some(_) => {}
            None => out.push(t),
        }
    }
    Ok(())
}

fn docs(out: &mut String, indent: &str, d: &Option<String>) {
    for l in d.iter().flat_map(|d| d.lines()) {
        let _ = writeln!(out, "{indent}/// {l}");
    }
}

fn key_param(m: &statex_runtime::Method) -> &'static str {
    ["actor", "actor-key", "callee-actor-key"].into_iter().find(|k| !m.params.iter().any(|p| p.name == *k)).unwrap()
}

fn client_wit(c: &Callee) -> Result<String> {
    let (ns, name) = client_package(&c.app);
    let mut s = format!("// {HEADER} from app {}. Do not edit.\npackage {}:{};\n", c.app, wid(&ns), wid(&name));
    for t in &c.types {
        if t.name == WORLD {
            bail!("app {}: actor type `{WORLD}` clashes with the generated world name", c.app);
        }
        let mut defs = Vec::new();
        for m in &t.methods {
            let ctx = format!("app {} {}.{}", c.app, t.name, m.name);
            for p in &m.params {
                collect(&p.ty, &mut defs, &ctx)?;
            }
            if let Some(r) = &m.result {
                collect(r, &mut defs, &ctx)?;
            }
        }
        let ce = if defs.iter().any(|d| named(d) == Some("call-error")) { "statex-call-error" } else { "call-error" };
        s.push('\n');
        docs(&mut s, "", &t.docs);
        let _ = writeln!(s, "interface {} {{", wid(&t.name));
        if ce == "call-error" {
            let _ = writeln!(s, "  use {HOST_ACTORS}.{{call-error}};");
        } else {
            let _ = writeln!(s, "  use {HOST_ACTORS}.{{call-error as {ce}}};");
        }
        for d in &defs {
            s.push('\n');
            match d {
                Ty::Record { name, fields } => {
                    let _ = writeln!(s, "  record {} {{", wid(name));
                    for f in fields {
                        let _ = writeln!(s, "    {}: {},", wid(&f.name), wit_ty(&f.ty));
                    }
                }
                Ty::Variant { name, cases } => {
                    let _ = writeln!(s, "  variant {} {{", wid(name));
                    for c in cases {
                        match &c.ty {
                            Some(t) => writeln!(s, "    {}({}),", wid(&c.name), wit_ty(t)),
                            None => writeln!(s, "    {},", wid(&c.name)),
                        }?;
                    }
                }
                Ty::Enum { name, cases } => {
                    let _ = writeln!(s, "  enum {} {{", wid(name));
                    for c in cases {
                        let _ = writeln!(s, "    {},", wid(c));
                    }
                }
                Ty::Flags { name, flags } => {
                    let _ = writeln!(s, "  flags {} {{", wid(name));
                    for f in flags {
                        let _ = writeln!(s, "    {},", wid(f));
                    }
                }
                _ => unreachable!(),
            }
            s.push_str("  }\n");
        }
        for m in &t.methods {
            s.push('\n');
            docs(&mut s, "  ", &m.docs);
            let mut params = vec![format!("{}: string", key_param(m))];
            params.extend(m.params.iter().map(|p| format!("{}: {}", wid(&p.name), wit_ty(&p.ty))));
            let ok = m.result.as_ref().map_or("_".into(), wit_ty);
            let _ = writeln!(s, "  {}: func({}) -> result<{ok}, {ce}>;", wid(&m.name), params.join(", "));
        }
        s.push_str("}\n");
    }
    let _ = writeln!(s, "\nworld {WORLD} {{");
    for t in &c.types {
        let _ = writeln!(s, "  import {};", wid(&t.name));
    }
    s.push_str("}\n");
    Ok(s)
}

// ---------- Rust ----------

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
    "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
    "trait", "true", "type", "unsafe", "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box",
    "do", "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
];

/// wit-bindgen's identifier for a kebab-case name.
pub(crate) fn rid(s: &str) -> String {
    let snake = s.replace('-', "_");
    if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("{snake}_")
    } else {
        snake
    }
}

fn pascal(s: &str) -> String {
    s.split('-').filter(|p| !p.is_empty()).map(|p| p[..1].to_uppercase() + &p[1..]).collect()
}

const CALL_ERROR: &str = "statex_guest::actors::CallError";

fn tuple(items: Vec<String>) -> String {
    if items.len() == 1 {
        format!("({},)", items[0])
    } else {
        format!("({})", items.join(", "))
    }
}

/// Owned Rust type, as wit-bindgen renders results and fields.
fn owned(t: &Ty) -> String {
    match t {
        Ty::Bool => "bool".into(),
        Ty::U8 => "u8".into(),
        Ty::U16 => "u16".into(),
        Ty::U32 => "u32".into(),
        Ty::U64 => "u64".into(),
        Ty::S8 => "i8".into(),
        Ty::S16 => "i16".into(),
        Ty::S32 => "i32".into(),
        Ty::S64 => "i64".into(),
        Ty::F32 => "f32".into(),
        Ty::F64 => "f64".into(),
        Ty::Char => "char".into(),
        Ty::String => "String".into(),
        Ty::List { element } => format!("Vec<{}>", owned(element)),
        Ty::Option { inner } => format!("Option<{}>", owned(inner)),
        Ty::Result { ok, err } => format!(
            "Result<{}, {}>",
            ok.as_deref().map_or("()".into(), owned),
            err.as_deref().map_or("()".into(), owned)
        ),
        Ty::Tuple { items } => tuple(items.iter().map(owned).collect()),
        Ty::Record { name, .. } | Ty::Variant { name, .. } | Ty::Enum { name, .. } | Ty::Flags { name, .. } => pascal(name),
    }
}

fn borrows(t: &Ty) -> bool {
    matches!(t, Ty::String | Ty::List { .. }) || children(t).into_iter().any(borrows)
}

/// Parameter type of an imported function, as wit-bindgen renders it:
/// strings and lists are borrowed, and so are records and variants that
/// contain them; everything else is passed by value.
fn param(t: &Ty) -> String {
    match t {
        Ty::String => "&str".into(),
        Ty::List { element } => format!("&[{}]", owned(element)),
        Ty::Option { inner } => format!("Option<{}>", param(inner)),
        Ty::Result { ok, err } => format!(
            "Result<{}, {}>",
            ok.as_deref().map_or("()".into(), param),
            err.as_deref().map_or("()".into(), param)
        ),
        Ty::Tuple { items } => tuple(items.iter().map(param).collect()),
        Ty::Record { .. } | Ty::Variant { .. } if borrows(t) => format!("&{}", owned(t)),
        _ => owned(t),
    }
}

struct RFn {
    name: String,
    wit_name: String,
    params: Vec<(String, String)>,
    ret: String,
}

fn rust_fns(t: &ActorType) -> Vec<RFn> {
    t.methods
        .iter()
        .map(|m| {
            let mut params = vec![(rid(key_param(m)), "&str".to_string())];
            params.extend(m.params.iter().map(|p| (rid(&p.name), param(&p.ty))));
            RFn {
                name: rid(&m.name),
                wit_name: m.name.clone(),
                params,
                ret: format!("Result<{}, {CALL_ERROR}>", m.result.as_ref().map_or("()".into(), owned)),
            }
        })
        .collect()
}

fn rust_shim(callees: &[Callee]) -> Result<String> {
    let mut s = format!(
        "// {HEADER}. Do not edit.\n\
         //! Typed clients of other statex apps' actors.\n\
         //!\n\
         //! In a component these call the callee through the host. In native\n\
         //! `cargo test` they call the stub installed with `<actor type>::stub(..)`\n\
         //! (per test thread); a call without a stub panics.\n\
         #![allow(dead_code, unused_imports, unused_variables, clippy::all)]\n"
    );
    let mut by_ns: BTreeMap<String, Vec<&Callee>> = BTreeMap::new();
    for c in callees {
        let (ns, name) = client_package(&c.app);
        if rid(&ns) != ns.replace('-', "_") || rid(&name) != name.replace('-', "_") {
            bail!("app {}: wit-bindgen cannot generate Rust package modules for keyword `{ns}:{name}`; use a non-keyword app namespace/name or a Python caller", c.app);
        }
        let _ = writeln!(
            s,
            "\n#[allow(non_snake_case)]\nmod bindings_{m} {{\n    wit_bindgen::generate!({{\n        path: \"wit\",\n        world: \"{ns}:{name}/{WORLD}\",\n        with: {{ \"{HOST_ACTORS}\": statex_guest::actors }},\n        additional_derives: [PartialEq],\n    }});\n}}",
            m = format!("{}__{}", rid(&ns), rid(&name))
        );
        by_ns.entry(ns).or_default().push(c);
    }
    for (ns, cs) in &by_ns {
        let _ = writeln!(s, "\npub mod {} {{", rid(ns));
        for c in cs {
            let (_, name) = client_package(&c.app);
            let bindings = format!("super::super::super::bindings_{}__{}", rid(ns), rid(&name));
            let _ = writeln!(s, "    /// Actors of app `{}`.\n    pub mod {} {{", c.app, rid(&name));
            for t in &c.types {
                let fns = rust_fns(t);
                let module = rid(&t.name);
                let tr = pascal(&t.name);
                let raw = format!("{bindings}::{}::{}::{module}", rid(ns), rid(&name));
                let mut defs = Vec::new();
                for m in &t.methods {
                    for p in &m.params {
                        collect(&p.ty, &mut defs, "")?;
                    }
                    if let Some(r) = &m.result {
                        collect(r, &mut defs, "")?;
                    }
                }
                let type_names: Vec<String> = defs.iter().filter_map(|d| named(d)).map(pascal).collect();
                docs(&mut s, "        ", &t.docs);
                let _ = writeln!(s, "        pub mod {module} {{");
                let _ = writeln!(s, "            use {raw} as raw;");
                if !type_names.is_empty() {
                    let _ = writeln!(s, "            pub use raw::{{{}}};", type_names.join(", "));
                }
                if !type_names.iter().any(|n| n == "CallError") {
                    let _ = writeln!(s, "            pub use {CALL_ERROR};");
                }
                if !fns.is_empty() {
                    let names: Vec<_> = fns.iter().map(|f| f.name.clone()).collect();
                    let _ = writeln!(s, "\n            #[cfg(target_arch = \"wasm32\")]\n            pub use raw::{{{}}};", names.join(", "));
                }
                let _ = writeln!(
                    s,
                    "\n            /// Test double for `{}` actors of app `{}`; install with [`stub`].\n            /// Methods not overridden panic.\n            pub trait {tr} {{",
                    t.name, c.app
                );
                for f in &fns {
                    let ps: Vec<_> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
                    let _ = writeln!(
                        s,
                        "                fn {}(&self, {}) -> {} {{\n                    panic!(\"{} {}.{} was called without a stub; implement it in the `{tr}` stub\")\n                }}",
                        f.name,
                        ps.join(", "),
                        f.ret,
                        c.app,
                        t.name,
                        f.wit_name
                    );
                }
                s.push_str("            }\n");
                let _ = writeln!(
                    s,
                    "\n            #[cfg(not(target_arch = \"wasm32\"))]\n            mod native {{\n                use super::*;\n                use std::{{cell::RefCell, rc::Rc}};\n\n                thread_local! {{\n                    static STUB: RefCell<Option<Rc<dyn {tr}>>> = RefCell::new(None);\n                }}\n\n                /// Routes calls on this thread to `s`.\n                pub fn stub(s: impl {tr} + 'static) {{\n                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));\n                }}\n\n                /// Removes this thread's stub.\n                pub fn clear_stub() {{\n                    STUB.with(|c| *c.borrow_mut() = None);\n                }}\n\n                fn current() -> Rc<dyn {tr}> {{\n                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {{\n                        panic!(\"{app} {ty} was called without a stub; call statex_calls::{path}::stub(..) first\")\n                    }})\n                }}",
                    app = c.app,
                    ty = t.name,
                    path = module_path(&c.app, &t.name).trim_start_matches("statex_calls::"),
                );
                for f in &fns {
                    let ps: Vec<_> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
                    let args: Vec<_> = f.params.iter().map(|(n, _)| n.clone()).collect();
                    let _ = writeln!(
                        s,
                        "\n                pub fn {}({}) -> {} {{\n                    current().{}({})\n                }}",
                        f.name,
                        ps.join(", "),
                        f.ret,
                        f.name,
                        args.join(", ")
                    );
                }
                if !fns.is_empty() {
                    s.push_str("\n                // Fails to compile if these signatures drift from wit-bindgen's.\n                const _: () = {\n");
                    for f in &fns {
                        let ts: Vec<_> = f.params.iter().map(|(_, t)| t.clone()).collect();
                        let _ = writeln!(s, "                    let _: fn({}) -> {} = raw::{};", ts.join(", "), f.ret, f.name);
                    }
                    s.push_str("                };\n");
                }
                s.push_str("            }\n\n            #[cfg(not(target_arch = \"wasm32\"))]\n            pub use native::*;\n        }\n");
            }
            s.push_str("    }\n");
        }
        s.push_str("}\n");
    }
    Ok(s)
}

/// `with` entries for the app's own `wit_bindgen::generate!`, so it reuses
/// the shim's bindings for the imported client interfaces.
pub fn with_entries(callees: &[Callee]) -> Vec<String> {
    let mut v = vec![format!("\"{HOST_ACTORS}\": statex_guest::actors,")];
    for c in callees {
        let (ns, name) = client_package(&c.app);
        for t in &c.types {
            v.push(format!(
                "\"{ns}:{name}/{}\": crate::statex_calls::{}::{}::{},",
                t.name,
                rid(&ns),
                rid(&name),
                rid(&t.name)
            ));
        }
    }
    v
}

/// Rust path of the shim module of a callee actor type.
pub fn module_path(app: &str, actor_type: &str) -> String {
    let (ns, name) = client_package(app);
    format!("statex_calls::{}::{}::{}", rid(&ns), rid(&name), rid(actor_type))
}

/// `import` lines for the app's world.
pub fn imports(callees: &[Callee]) -> Vec<String> {
    callees
        .iter()
        .flat_map(|c| {
            let (ns, name) = client_package(&c.app);
            c.types.iter().map(move |t| format!("import {}:{}/{};", wid(&ns), wid(&name), wid(&t.name)))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use statex_runtime::{Case, Field, Method, Param};

    fn kv() -> Callee {
        let entry = Ty::Record {
            name: "entry".into(),
            fields: vec![
                Field { name: "key".into(), ty: Ty::String },
                Field { name: "value".into(), ty: Ty::List { element: Box::new(Ty::U8) } },
            ],
        };
        let point = Ty::Record { name: "point".into(), fields: vec![Field { name: "x".into(), ty: Ty::S32 }] };
        let err = Ty::Variant {
            name: "kv-error".into(),
            cases: vec![Case { name: "missing".into(), ty: None }, Case { name: "other".into(), ty: Some(Ty::String) }],
        };
        Callee {
            app: "demo/db".into(),
            types: vec![ActorType {
                name: "kv".into(),
                export: "demo:db/kv".into(),
                docs: Some("A key-value store.".into()),
                methods: vec![
                    Method {
                        name: "put".into(),
                        params: vec![Param { name: "e".into(), ty: entry.clone() }, Param { name: "at".into(), ty: point }],
                        result: None,
                        docs: None,
                    },
                    Method {
                        name: "get".into(),
                        params: vec![Param { name: "actor".into(), ty: Ty::String }],
                        result: Some(Ty::Result {
                            ok: Some(Box::new(Ty::Option { inner: Box::new(entry) })),
                            err: Some(Box::new(err)),
                        }),
                        docs: Some("Reads one entry.".into()),
                    },
                ],
                alarm: None,
            }],
        }
    }

    #[test]
    fn client_wit_parses_and_round_trips() {
        let c = kv();
        let wit = client_wit(&c).unwrap();
        assert!(wit.contains("get: func(actor-key: string, actor: string) -> result<result<option<entry>, kv-error>, call-error>;"), "{wit}");
        let back = parse_client(Path::new("client.wit"), &wit).unwrap();
        assert_eq!(back.app, "demo/db");
        assert_eq!(back.types[0].methods, c.types[0].methods);
        assert_eq!(client_wit(&Callee { app: back.app, types: vec![ActorType { docs: c.types[0].docs.clone(), ..back.types[0].clone() }] }).unwrap(), wit);
    }

    #[test]
    fn rust_param_rules() {
        let c = kv();
        let f = rust_fns(&c.types[0]);
        assert_eq!(f[0].params[1].1, "&Entry");
        assert_eq!(f[0].params[2].1, "Point");
        assert_eq!(f[0].ret, format!("Result<(), {CALL_ERROR}>"));
        assert_eq!(f[1].params[0].0, "actor_key");
        assert_eq!(f[1].ret, format!("Result<Result<Option<Entry>, KvError>, {CALL_ERROR}>"));
    }

    #[test]
    fn simple_and_namespaced_clients_preserve_callee_identity() {
        for app in ["shop", "payments/shop", "type", "interface/type"] {
            let mut c = kv();
            c.app = app.into();
            let wit = client_wit(&c).unwrap();
            let back = parse_client(Path::new("client.wit"), &wit).unwrap();
            assert_eq!(back.app, app);
            assert_eq!(back.types[0].methods, c.types[0].methods);
        }
        assert_eq!(module_path("shop", "kv"), "statex_calls::statex::shop::kv");
        assert_eq!(module_path("payments/shop", "kv"), "statex_calls::payments::shop::kv");
    }

    #[test]
    fn explicit_source_path_must_name_the_requested_app() {
        let d = tempfile::tempdir_in(".").unwrap();
        let caller = d.path().join("caller");
        let callee = d.path().join("source");
        crate::scaffold::new_python_project("caller", &caller, "counter", None).unwrap();
        crate::scaffold::new_python_project("shop", &callee, "counter", None).unwrap();
        let mut p = Project::find(&caller).unwrap();
        p.cfg.calls.paths.insert("shop".into(), PathBuf::from("../source"));
        assert_eq!(callee_root(&p, None, "shop").unwrap().unwrap(), callee.canonicalize().unwrap());
        p.cfg.calls.paths.insert("wrong".into(), PathBuf::from("../source"));
        assert!(callee_root(&p, None, "wrong").unwrap_err().to_string().contains("whose manifest names"));
    }

    #[test]
    fn namespace_boundaries_do_not_collide_in_generated_names() {
        assert_ne!(client_file("a/b-c"), client_file("a-b/c"));
        let mut first = kv();
        first.app = "a/b-c".into();
        let mut second = kv();
        second.app = "a-b/c".into();
        let shim = rust_shim(&[first, second]).unwrap();
        assert!(shim.contains("mod bindings_a__b_c"));
        assert!(shim.contains("mod bindings_a_b__c"));
        assert!(shim.contains("#[allow(non_snake_case)]\nmod bindings_a__b_c"));
        assert!(shim.contains("#[allow(non_snake_case)]\nmod bindings_a_b__c"));
        assert_eq!(shim.matches("#[allow(non_snake_case)]").count(), 2);
    }

    #[test]
    fn remote_clients_require_the_unambiguous_directory_layout() {
        let d = tempfile::tempdir_in(".").unwrap();
        let root = d.path().join("caller");
        crate::scaffold::new_python_project("caller", &root, "counter", None).unwrap();
        let mut p = Project::find(&root).unwrap();
        p.cfg.calls.apps.push("demo/db".into());
        let old = PathBuf::from("wit/deps/demo-db/client.wit");
        let old_files = BTreeMap::from([(old, client_wit(&kv()).unwrap())]);
        write(&p, None, &old_files).unwrap();
        assert!(local_plan(&p, None).unwrap_err().to_string().contains("no client interface for app demo/db"));
    }

    #[test]
    fn rust_package_keyword_limit_has_an_actionable_error() {
        let mut c = kv();
        c.app = "type".into();
        assert!(rust_shim(&[c]).unwrap_err().to_string().contains("wit-bindgen cannot generate Rust package modules"));
    }
}
