use statex_guest::{context, params, sql};

mod statex_calls;

wit_bindgen::generate!({
    path: "wit",
    world: "app",
    additional_derives: [PartialEq],
    // Reuse the typed clients generated by `statex calls sync`.
    with: {
        "statex:host/actors@0.1.0": statex_guest::actors,
        "demo:db/kv": crate::statex_calls::demo::db::kv,
    },
});

use exports::local::demo_rustdemo::counter as counter;
use statex_calls::demo::db::kv;

/// The demo/db `kv` actor that stores saved counters.
const STORE: &str = "counters";

struct App;

// Each call runs inside its own transaction against this actor's database.
impl counter::Guest for App {
    fn increment(by: i64) -> i64 {
        sql::execute("UPDATE counter SET value = value + ?1 WHERE id = 0", params![by]).unwrap();
        Self::get()
    }

    fn get() -> i64 {
        sql::query_scalar("SELECT value FROM counter WHERE id = 0", &[]).unwrap().unwrap_or(0)
    }

    // A typed call into another app's actor: it runs (and commits) on its own,
    // possibly on another node, while this method waits for the result.
    fn save() -> Result<i64, String> {
        let value = Self::get();
        kv::put(STORE, &context::key(), &value.to_string()).map_err(|e| e.to_string())?;
        Ok(value)
    }

    fn saved() -> Result<Option<String>, String> {
        kv::get(STORE, &context::key()).map_err(|e| e.to_string())
    }
}

export!(App);

#[cfg(test)]
mod tests {
    use super::*;
    use counter::Guest as _;
    use statex_guest::testing::call;
    use std::cell::RefCell;
    use std::collections::HashMap;

    #[test]
    fn increments_per_key() {
        assert_eq!(call("counter", "alice", || App::increment(2)), 2);
        assert_eq!(call("counter", "alice", || App::increment(3)), 5);
        assert_eq!(call("counter", "bob", App::get), 0);
    }

    /// An in-memory stand-in for demo/db's kv actors.
    #[derive(Default)]
    struct FakeKv(RefCell<HashMap<(String, String), String>>);

    impl kv::Kv for FakeKv {
        fn put(&self, actor: &str, key: &str, value: &str) -> Result<(), kv::CallError> {
            self.0.borrow_mut().insert((actor.into(), key.into()), value.into());
            Ok(())
        }
        fn get(&self, actor: &str, key: &str) -> Result<Option<String>, kv::CallError> {
            Ok(self.0.borrow().get(&(actor.into(), key.into())).cloned())
        }
    }

    #[test]
    fn saves_to_demo_db() {
        kv::stub(FakeKv::default());
        call("counter", "alice", || App::increment(7));
        assert_eq!(call("counter", "alice", App::save), Ok(7));
        assert_eq!(call("counter", "alice", App::saved), Ok(Some("7".into())));
        assert_eq!(call("counter", "bob", App::saved), Ok(None));
    }

    struct Down;
    impl kv::Kv for Down {
        fn put(&self, _: &str, _: &str, _: &str) -> Result<(), kv::CallError> {
            Err(kv::CallError::Unavailable("demo/db is down".into()))
        }
    }

    #[test]
    fn reports_call_errors() {
        kv::stub(Down);
        assert_eq!(call("counter", "alice", App::save), Err("unavailable: demo/db is down".into()));
    }
}
