// Generated by `statex calls sync`. Do not edit.
//! Typed clients of other statex apps' actors.
//!
//! In a component these call the callee through the host. In native
//! `cargo test` they call the stub installed with `<actor type>::stub(..)`
//! (per test thread); a call without a stub panics.
#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

#[allow(non_snake_case)]
mod bindings_demo__db {
    wit_bindgen::generate!({
        path: "wit",
        world: "demo:db/statex-calls",
        with: { "statex:host/actors@0.1.0": statex_guest::actors },
        additional_derives: [PartialEq],
    });
}

pub mod demo {
    /// Actors of app `demo/db`.
    pub mod db {
        /// Each exported interface is an actor type; each function is a method.
        /// Every key (e.g. "alice") is an independent actor with its own SQLite database.
        pub mod kv {
            use super::super::super::bindings_demo__db::demo::db::kv as raw;
            pub use raw::{Entry};
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{put, get, delete, scan};

            /// Test double for `kv` actors of app `demo/db`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Kv {
                fn put(&self, actor: &str, key: &str, value: &str) -> Result<(), statex_guest::actors::CallError> {
                    panic!("demo/db kv.put was called without a stub; implement it in the `Kv` stub")
                }
                fn get(&self, actor: &str, key: &str) -> Result<Option<String>, statex_guest::actors::CallError> {
                    panic!("demo/db kv.get was called without a stub; implement it in the `Kv` stub")
                }
                fn delete(&self, actor: &str, key: &str) -> Result<bool, statex_guest::actors::CallError> {
                    panic!("demo/db kv.delete was called without a stub; implement it in the `Kv` stub")
                }
                fn scan(&self, actor: &str, prefix: &str) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    panic!("demo/db kv.scan was called without a stub; implement it in the `Kv` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Kv>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Kv + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                pub(super) fn current() -> Rc<dyn Kv> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("demo/db kv was called without a stub; call statex_calls::demo::db::kv::stub(..) first")
                    })
                }

                pub fn put(actor: &str, key: &str, value: &str) -> Result<(), statex_guest::actors::CallError> {
                    current().put(actor, key, value)
                }

                pub fn get(actor: &str, key: &str) -> Result<Option<String>, statex_guest::actors::CallError> {
                    current().get(actor, key)
                }

                pub fn delete(actor: &str, key: &str) -> Result<bool, statex_guest::actors::CallError> {
                    current().delete(actor, key)
                }

                pub fn scan(actor: &str, prefix: &str) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    current().scan(actor, prefix)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, &str, &str) -> Result<(), statex_guest::actors::CallError> = raw::put;
                    let _: fn(&str, &str) -> Result<Option<String>, statex_guest::actors::CallError> = raw::get;
                    let _: fn(&str, &str) -> Result<bool, statex_guest::actors::CallError> = raw::delete;
                    let _: fn(&str, &str) -> Result<Vec<Entry>, statex_guest::actors::CallError> = raw::scan;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;

            #[cfg(not(target_arch = "wasm32"))]
            impl statex_guest::testing::ToJson for Entry {
                fn to_json(&self) -> Result<statex_guest::serde_json::Value, statex_guest::actors::CallError> {
                    use statex_guest::{serde_json::{Value, json}, testing::to_json};
                    Ok(Value::Object([
                        ("key".into(), to_json(&self.key)?),
                        ("value".into(), to_json(&self.value)?),
                    ].into_iter().collect()))
                }
            }

            /// Transactional deferred calls; returns a job ID, not the method result.
            pub mod spawn {
                use super::*;
                pub fn put(actor: &str, key: &str, value: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_put(actor, key, value).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?, statex_guest::testing::to_json(&value)?];
                        let __statex_id = statex_guest::actors::spawn_after(std::time::Duration::ZERO, "demo/db", "kv", actor, "put", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        let __statex_arg1 = (value).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().put(&__statex_key, (&__statex_arg0).as_str(), (&__statex_arg1).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn get(actor: &str, key: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_get(actor, key).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?];
                        let __statex_id = statex_guest::actors::spawn_after(std::time::Duration::ZERO, "demo/db", "kv", actor, "get", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().get(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn delete(actor: &str, key: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_delete(actor, key).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?];
                        let __statex_id = statex_guest::actors::spawn_after(std::time::Duration::ZERO, "demo/db", "kv", actor, "delete", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().delete(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn scan(actor: &str, prefix: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_scan(actor, prefix).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&prefix)?];
                        let __statex_id = statex_guest::actors::spawn_after(std::time::Duration::ZERO, "demo/db", "kv", actor, "scan", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (prefix).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().scan(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
            }

            /// Transactional deferred calls; returns a job ID, not the method result.
            pub mod spawn_after {
                use super::*;
                pub fn put(__statex_delay: std::time::Duration, actor: &str, key: &str, value: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_after_put(actor, statex_guest::actors::delay_ms(__statex_delay)?, key, value).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?, statex_guest::testing::to_json(&value)?];
                        let __statex_id = statex_guest::actors::spawn_after(__statex_delay, "demo/db", "kv", actor, "put", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        let __statex_arg1 = (value).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().put(&__statex_key, (&__statex_arg0).as_str(), (&__statex_arg1).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn get(__statex_delay: std::time::Duration, actor: &str, key: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_after_get(actor, statex_guest::actors::delay_ms(__statex_delay)?, key).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?];
                        let __statex_id = statex_guest::actors::spawn_after(__statex_delay, "demo/db", "kv", actor, "get", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().get(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn delete(__statex_delay: std::time::Duration, actor: &str, key: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_after_delete(actor, statex_guest::actors::delay_ms(__statex_delay)?, key).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&key)?];
                        let __statex_id = statex_guest::actors::spawn_after(__statex_delay, "demo/db", "kv", actor, "delete", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (key).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().delete(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
                pub fn scan(__statex_delay: std::time::Duration, actor: &str, prefix: &str) -> Result<String, statex_guest::actors::CallError> {
                    #[cfg(target_arch = "wasm32")]
                    { raw::statex_spawn_after_scan(actor, statex_guest::actors::delay_ms(__statex_delay)?, prefix).map(|reply| reply.id) }
                    #[cfg(not(target_arch = "wasm32"))]
                    {
                        let __statex_args = vec![statex_guest::testing::to_json(&prefix)?];
                        let __statex_id = statex_guest::actors::spawn_after(__statex_delay, "demo/db", "kv", actor, "scan", &__statex_args)?;
                        let __statex_key = actor.to_string();
                        let __statex_arg0 = (prefix).to_string();
                        statex_guest::testing::attach_job(&__statex_id, move || {
                            let value = native::current().scan(&__statex_key, (&__statex_arg0).as_str())?;
                            let __statex_result = statex_guest::testing::to_json(&value)?;
                            Ok(__statex_result)
                        });
                        Ok(__statex_id)
                    }
                }
            }
        }
    }
}
