import React, { useState } from "react";
import { Section, Card, Note, Source, Code, Table, Flow, Detail, Badge, ChapterLink, Icon } from "./ui.jsx";
import { Onion, Topology, RequestStepper, LeaseLab, CasRace, RestoreLab, FailureLab, PatternLab } from "./interactives.jsx";
import { errors } from "./model.mjs";

export function Overview() {
  return <>
    <Note title="A framework with replaceable defaults">The diagrams and labs below illustrate the default SQLite/WAL state backend. SQLite, the shared object store, HTTP/log services, and additional guest-to-host capabilities have explicit extension interfaces. A standalone app such as <code>hello</code> needs no team namespace or repository workspace. See <code>docs/extensions/</code> for implementation contracts.</Note>
    <div className="hero-facts"><span><Icon name="cube" size={16}/> WebAssembly compute</span><span><Icon name="database" size={16}/> SQLite per actor</span><span><Icon name="shield" size={16}/> Object-store durability</span></div>
    <Onion/>
    <Section eyebrow="The 30-second version" title="Bring behavior to the state.">
      <p className="section-lead">Instead of loading an entity from a remote database for every operation, call an actor that owns a private database. StateX finds its current node, runs your method, and makes committed pages durable before acknowledging a write.</p>
      <Topology/>
      <div className="grid three"><Card title="One identity" icon="cube"><p><code>(app, type, key)</code> names the unit of isolation. A key creates an actor on first use; there is no per-actor route registration.</p></Card><Card title="One local transaction" icon="database"><p>Calls to the same actor are serialized. SQL updates and pending migrations share one host-controlled transaction.</p></Card><Card title="A portable home" icon="layers"><p>Resident memory and local disk can disappear. The next owner rebuilds the database from the shared object store.</p></Card></div>
    </Section>
    <Section eyebrow="Separate these ideas" title="Code, identity, and state are not the same thing.">
      <Flow label="App, type, actor identity, private database" nodes={[{ kicker: "APP", title: "demo/hello", text: "One deployed component" }, { kicker: "ACTOR TYPE", title: "counter", text: "One WIT interface" }, { kicker: "ACTOR KEY", title: "alice", text: "One logical identity" }, { kicker: "STATE", title: "SQLite", text: "One private database", tone: "mint" }]}/>
      <Code title="Generated Python client / conceptual example">{`app = HelloApp("http://any-node:9876")\napp.counter("alice").increment(by=1)\n# POST /v1/apps/demo/hello/actors/counter/alice/increment\n# The actual generated class name follows the app's name.`}</Code>
      <Note title="Durable state is SQLite, not the whole Wasm process">The component instance is resident and reusable, but guest memory is not checkpointed to the store. Persist anything you need after eviction, a code update, or a node crash.</Note>
    </Section>
    <Section eyebrow="What this is / what this is not" title="A focused execution engine, not every distributed system.">
      <div className="grid two"><Card title="What the engine supplies" icon="check" tone="mint"><p>Actor identity, request routing, serialized execution, private SQLite, object-store replication, ownership coordination, typed actor calls, and component deployment.</p></Card><Card title="What your application supplies" icon="branch"><p>Idempotency, cross-actor protocols, external-effect coordination, business authorization, schedulers, durable work delivery, and application-specific retry policies.</p></Card></div>
      <Note title="Read the pictures as a protocol, not a formal proof" tone="amber">The documented guarantees assume working conditional writes, read/list consistency, bounded clock skew, and correct operational configuration. The failure and reference chapters call out the exact implementation boundaries.</Note>
      <Source files="README.md; docs/architecture.md; docs/guarantees.md"/>
    </Section>
  </>;
}

const components = [
  { name: "HTTP edge & addressing", icon: "branch", file: "crates/node/src/api.rs", role: "Turn a generic route into an Invocation.", input: "Raw URI, HTTP verb, JSON body, app metadata.", output: "Public outcome or an internal HMAC-verified call.", details: "The parser recognizes app or team/app before actors/schema. Keys are percent-encoded single segments. An empty body becomes null; named or positional arguments are resolved against WIT. The public API starts an empty call chain; callers cannot inject one.", boundary: "Routing is not a user-authentication layer. Protect public endpoints with your deployment's gateway and network controls." },
  { name: "Node & actor slots", icon: "cube", file: "crates/node/src/node.rs", role: "Own the routing and acknowledgement state machine.", input: "Invocation, current deployment, lease, owner records.", output: "Local execution, signed forwarding, takeover, or an explicit error.", details: "An async mutex protects each actor slot. It spans local execution and durability; snapshot work can retain it beyond the reply. Other actors have their own slots. Placement is first-touch-wins, not hash-based placement or proactive load balancing.", boundary: "One hot key stays serialized. Adding nodes helps independent keys, not a single actor's transaction throughput." },
  { name: "Lease & ownership", icon: "clock", file: "crates/node/src/lease.rs + owner.rs", role: "Distinguish liveness, process identity, and actor ownership.", input: "Node session, clock, TTL, owner ETag.", output: "A live owner, a CAS winner, or a fenced node.", details: "Node lease renewal is per node, not per actor. An owner record refers to a node and its process session and carries an actor epoch. The record remains after idle release or deletion so epochs never reset.", boundary: "The lease margin depends on clock discipline. ETags are store-version tokens; they are not actor epochs." },
  { name: "Resident actor", icon: "database", file: "crates/node/src/actor.rs", role: "Bind a component, database, and WAL cursor for one epoch.", input: "Actor ID, code, restored SQLite image, call operation.", output: "Guest outcome plus an optional committed page segment.", details: "Tracks txid, snapshot_txid, owner_etag, code pointer, lazy instance, migration status, and last-used time. On new code, it drops the old instance and rechecks migrations. A trap resets the instance. Dropping the actor removes its local directory.", boundary: "Only SQLite participates in commit/rollback. A local instance or in-memory field is not durable business state." },
  { name: "Wasmtime runtime", icon: "code", file: "crates/runtime/src/{lib,host,json,calls,manifest,compat}.rs", role: "Link and execute a typed, resource-bounded component.", input: "WIT-derived manifest, Wasm bytes, identity and host imports.", output: "Typed values, domain error, bad arguments, or a guest trap.", details: "Manifest extraction defines actor types and migrations. JSON lowering/lifting bridges clients and WIT. Host bindings mediate SQL and external access; dynamic client imports route actor calls. Compatibility logic protects existing surfaces during deploy.", boundary: "This is a component sandbox, not an unrestricted native process or a built-in long-running job scheduler." },
  { name: "LTX-style page log", icon: "layers", file: "crates/ltx/src/lib.rs", role: "Capture committed SQLite pages and plan deterministic restore.", input: "SQLite WAL frames; ordered snapshot/segment object names.", output: "Checksummed STXLTX01 segments and a contiguous restore plan.", details: "WalTail watches WAL salts and offsets, keeps the final image of each changed page, and only accepts committed frames. Segments record epoch, txid, page size, final database page count, pages, and CRC32.", boundary: "This is StateX's own LTX-style format, not a promise of compatibility with another product's LTX files. It replicates page images, not SQL commands." },
  { name: "Object store", icon: "shield", file: "crates/store/src/{lib,local,azure}.rs", role: "Provide versioned conditional writes and durable objects.", input: "Keys, bytes/files, ETags and range requests.", output: "Objects with versions, clean precondition rejection, or an ambiguous error.", details: "Azure uses Blob APIs and supports ADLS Gen2 via the Blob endpoint. The local backend uses per-object advisory file locks, temporary files, sync, rename, and ETag metadata. File upload/download APIs stream snapshots.", boundary: "The local backend is intended for development and tests on one machine. Do not assume arbitrary shared/network filesystems preserve its locking or crash semantics." },
  { name: "CLI, SDKs & registry", icon: "book", file: "crates/cli; crates/guest; sdk; registry", role: "Turn authoring contracts into deployable apps and typed clients.", input: "statex.toml, WIT, migrations, implementations and workspace layout.", output: "Wasm, manifests, generated caller bindings, Python clients and registry entries.", details: "The CLI scaffolds Rust/Python apps, builds and verifies them, checks compatibility, syncs call interfaces, and deploys. Guest SDKs expose host capabilities; the Python client SDK invokes the generic HTTP API.", boundary: "The registry describes APIs for development. Live actor placement comes from owner.json, not the registry." }
];

function ComponentExplorer() {
  const [selected, setSelected] = useState(0);
  const c = components[selected];
  return <div className="component-explorer"><div className="component-list" aria-label="Select a component">{components.map((item, i) => <button key={item.name} aria-pressed={selected === i} onClick={() => setSelected(i)}><Icon name={item.icon}/><span>{item.name}</span><span className="component-index">{String(i + 1).padStart(2, "0")}</span></button>)}</div><div className="component-detail" aria-live="polite"><Badge>COMPONENT {selected + 1} / {components.length}</Badge><h3>{c.name}</h3><p className="big-copy">{c.role}</p><div className="io-row"><div><span className="mini-label">Receives</span><p>{c.input}</p></div><Icon name="arrow"/><div><span className="mini-label">Produces</span><p>{c.output}</p></div></div><p>{c.details}</p><Note title="Boundary" tone="amber">{c.boundary}</Note><Source files={c.file}/></div></div>;
}

export function Architecture() {
  return <>
    <Topology/>
    <Section eyebrow="Component atlas" title="Click a boundary. See its contract."><ComponentExplorer/></Section>
    <Section eyebrow="Inside one node" title="Many actors; independent serial lanes.">
      <div className="node-anatomy"><div className="node-header"><Icon name="cube"/><strong>One node process</strong><Badge>one shared node lease</Badge></div><div className="grid three">{["alice", "bob", "checkout"].map((name, i) => <div className="actor-lane" key={name}><div className="mini-label">Actor slot {i + 1}</div><h3>{name}</h3><div className="queue-dots"><span/><span/><span/><Icon name="arrow" size={18}/><Icon name="shield" size={20}/></div><p>slot mutex</p><Flow vertical nodes={[{ title: "Wasm instance", text: "Resident, not durable" }, { title: "SQLite + WAL", text: "Private to this actor", tone: "mint" }]}/></div>)}</div><div className="node-bottom">Shared app code cache · peer client · runtime engine · lease renewal · deploy polling · idle eviction</div></div>
      <Note title="Serial does not mean a built-in message queue">Concurrent callers wait on an in-memory slot mutex. There is no persisted inbox, durable buffering, or automatic background execution in this mechanism. A request lost before durable application still needs a client or driver to retry.</Note>
    </Section>
    <Section eyebrow="Two kinds of traffic" title="The store is both coordinator and recovery medium.">
      <div className="grid two"><Card title="Coordination & configuration" icon="clock" tone="mint"><p><code>nodes/</code> leases identify live sessions. <code>owner.json</code> points to the current actor owner. <code>deploy/</code> publishes code versions. <code>fleet/peer-auth.json</code> supplies peer signing material.</p></Card><Card title="Durable actor data" icon="database" tone="lavender"><p><code>ltx/e&lt;epoch&gt;/</code> contains snapshots and transaction segments. These are used for restore and compaction, not queried as application records during every SQL read.</p></Card></div>
      <Table headers={["Question", "Source of truth", "Not this"]} rows={[["Where should a call run?", "owner record + matching live node session", "A consistent-hash ring or client-side shard map"], ["Which app code should a node load?", "deploy/<app>/current.json", "Per-actor route registration"], ["What survives lost local disk?", "Snapshot + contiguous segments", "Wasm memory or local SQLite alone"], ["Who wins competing activation?", "If-Match / If-None-Match conditional write", "A last-writer-wins unconditional PUT"]]}/>
      <Source files="crates/node/src/node.rs:29-131, 293-431; crates/node/src/lib.rs:79-156"/>
    </Section>
  </>;
}

export function Journey() {
  return <>
    <RequestStepper/>
    <Section eyebrow="A gate, not a return statement" title="Three things must line up for a write reply.">
      <div className="ack-equation"><div><Icon name="layers"/><strong>Segment uploaded</strong><small>committed pages in the store</small></div><span>+</span><div><Icon name="clock"/><strong>Lease valid</strong><small>inside the local safety margin</small></div><span>+</span><div><Icon name="shield"/><strong>Still the owner</strong><small>owned + node + session + epoch</small></div><span>=</span><div className="ack-success"><strong>ACK</strong><small>successful write response</small></div></div>
      <p>A method return is only the input to the host's decision. Local SQLite commit happens before object-store upload. Failure between these steps can make the client's outcome uncertain; the engine drops the resident actor rather than continuing on potentially ambiguous local state.</p>
      <Note title="Exact source behavior: the read path is different" tone="amber">The post-upload lease and owner checks run only when WAL capture produces a segment. A genuinely no-write call skips that branch. The entry lease check is not a formal guarantee of linearizable reads across arbitrary delays. Also, the write branch checks lease validity before awaiting the owner GET; it does not perform a second lease check after that GET.</Note>
      <Source files="crates/node/src/node.rs:328-335, 434-518"/>
    </Section>
    <Section eyebrow="Take the cold path" title="Activation happens before the first method.">
      <Flow nodes={[{ title: "Acquire", text: "Win owner.json CAS" }, { title: "Restore", text: "Snapshot + contiguous log" }, { title: "Open DB", text: "WAL / FULL sync" }, { title: "Snapshot", text: "Publish new epoch base", tone: "mint" }, { title: "Invoke", text: "Run first call" }]}/>
      <div className="grid two"><Card title="New or deleted actor" icon="cube"><p>Start fresh, using txid 0. A deleted record still retains the last epoch; recreation increments it. Initial activation uploads a baseline snapshot before lazy migrations and the first method.</p></Card><Card title="Previously existing actor" icon="database"><p>Clear the local replica directory. Find the newest usable epoch, download its newest snapshot, apply contiguous later segments, then checkpoint and upload that state into the new epoch.</p></Card></div>
      <Detail title="Why activation needs its own snapshot"><p>A new epoch becomes independent of older prefixes. Later stale writes to an old epoch cannot alter the selected new epoch's database image. An epoch with no snapshot is not a usable restore base; recovery can fall back to an older one.</p></Detail>
      <Detail title="What the lock actually covers"><p>The actor's slot mutex prevents concurrent local calls. It stays held while execution runs on a blocking thread and while pages are uploaded. If compaction is triggered, a background task retains the lock through checkpoint, snapshot upload, and garbage collection. A reply can already be returned while the next call waits for that task.</p></Detail>
    </Section>
    <Section eyebrow="Follow the response shape" title="Domain errors are different from execution failures.">
      <div className="grid two"><Code title="Successful increment">{`HTTP 200\n{"result": 42}`}</Code><Code title="Method returns err(E)">{`HTTP 422\n{"error": {\n  "code": "method_error",\n  "message": "method returned an error",\n  "detail": "insufficient-funds"\n}}`}</Code></div>
      <p>A successful top-level WIT <code>result&lt;T,E&gt;</code> is unwrapped into the HTTP result. A method-level error rolls back the actor transaction. Nested result values still use their own WIT-to-JSON representation.</p>
      <ChapterLink id="failures">Compare every failure window</ChapterLink>
    </Section>
  </>;
}

export function Leases() {
  return <>
    <div className="grid two"><Card title="Node lease: am I alive?" icon="clock" tone="mint"><p><code>nodes/&lt;id&gt;.json</code></p><p>One per node process. Contains node ID, random session, advertised internal URL, start time, and expiry. Renewed by conditional overwrite, normally every TTL / 3.</p></Card><Card title="Actor record: who owns this?" icon="shield" tone="lavender"><p><code>actors/&lt;app&gt;/&lt;type&gt;/&lt;key&gt;/owner.json</code></p><p>One per actor identity. Contains node, session, epoch, and owned / unowned / deleted state. It points to a node lease; it does not carry a separate actor TTL.</p></Card></div>
    <Section eyebrow="Time is part of the protocol" title="A safety gap separates old and new owners."><LeaseLab/></Section>
    <Section eyebrow="Versions, not wishful thinking" title="Two nodes can race. Only one can replace the record."><CasRace/><Source files="crates/node/src/owner.rs:56-96"/></Section>
    <Section eyebrow="State transitions" title="The actor record is never erased.">
      <Flow label="Actor ownership lifecycle" nodes={[{ title: "Missing", text: "No owner record yet" }, { title: "Owned · e1", text: "Conditional create", tone: "mint" }, { title: "Unowned · e1", text: "Idle or graceful release" }, { title: "Owned · e2", text: "Next touch + CAS", tone: "mint" }]}/>
      <Flow label="Deletion and recreation lifecycle" nodes={[{ title: "Owned · e2", text: "Existing database" }, { title: "Deleted · e2", text: "Conditional tombstone", tone: "amber" }, { title: "Owned · e3", text: "Next call creates fresh", tone: "mint" }]}/>
      <Table headers={["Situation", "Protocol response", "Why it matters"]} rows={[["Live owner, same session", "Forward to its advertise URL.", "The receiving node does not steal a busy actor."], ["Same node ID, new session", "Old owner's session no longer matches; takeover can be attempted.", "A restart is not the same process incarnation."], ["Expired / absent node lease", "CAS owner record to new node/session and epoch + 1.", "A node's lease expiry does not itself execute an actor."], ["CAS precondition fails", "Re-read; forward or try again based on the new record.", "The loser cannot assume ownership."], ["Idle release", "Keep epoch, set unowned, drop local actor.", "Next activation restores state with a higher epoch."], ["Delete", "CAS deleted, then attempt data cleanup.", "A tombstone preserves epoch monotonicity; subsequent use starts fresh."]]}/>
    </Section>
    <Section eyebrow="What fencing means" title="Stop trusting the old process.">
      <div className="grid three"><Card title="Renewal rejected" icon="alert"><p>A clean precondition rejection means the lease record changed. The node fences itself immediately when the renewal result is observed.</p></Card><Card title="Renewal too late" icon="clock"><p>Other store failures log a warning. If the node cannot renew inside the local deadline, the loop fences it. Requests cannot pass valid() after the cutoff.</p></Card><Card title="Drop & restart" icon="shield"><p>The node signals fencing and drops available resident slots. In production, <code>statex node</code> exits with code 3; a supervisor should restart it.</p></Card></div>
      <Note title="Fencing is not an undo operation" tone="amber">It cannot unsend HTTP, undo a separately committed callee, or promise that every in-flight function has synchronously stopped. Busy slots are not immediately cleared by try_lock-based drop_all; production process exit and per-call acknowledgement checks are important parts of the operational design.</Note>
      <Detail title="Who measures expiry, and when?"><p>Renewal computes the advertised expiry from the time before sending its store request, not from the response time. The local predicate is <code>now + max(TTL/5, 200ms) &lt; valid_until</code>. Peers use the stored expiry, matching the owner record's session. Keep node clocks aligned; making TTL tiny is not a free reduction in failover latency.</p></Detail>
      <Detail title="Graceful shutdown versus crash"><p>A graceful shutdown attempts actor release and then marks the node lease expired. This avoids waiting out a healthy TTL when store operations succeed. A crash cannot release anything; other nodes initially see the old lease as live, then compete after expiry. Neither path proactively migrates an actor without a request.</p></Detail>
      <Source files="crates/node/src/lease.rs; crates/node/src/owner.rs; crates/node/src/node.rs:585-611; crates/node/src/lib.rs:29-56, 95-107"/>
    </Section>
  </>;
}

export function Durability() {
  return <>
    <div className="grid two"><Card title="Local plane" icon="database"><p>Wasm instance → SQLite connection → database file + WAL. Fast, private to an actor, disposable after the durable log is published.</p><Badge tone="amber">NOT THE RECOVERY AUTHORITY</Badge></Card><Card title="Shared plane" icon="layers" tone="mint"><p>Object store → epoch snapshot → later transaction segments. Sufficient to reconstruct acknowledged database state under the documented assumptions.</p><Badge tone="green">DURABLE RECOVERY INPUT</Badge></Card></div>
    <Section eyebrow="From mutation to pages" title="Replicate the result, not a rerun of the method.">
      <Flow nodes={[{ title: "SQLite COMMIT", text: "WAL has committed frames" }, { title: "WalTail capture", text: "Final changed page images" }, { title: "Encode segment", text: "Metadata + pages + CRC32" }, { title: "Object PUT", text: "One txid in one epoch", tone: "mint" }]}/>
      <div className="page-demo" aria-label="Changed page illustration"><div><span className="mini-label">Database pages</span><div className="page-grid">{Array.from({ length: 12 }, (_, i) => <span key={i} className={[1, 4, 8].includes(i) ? "changed" : ""}>p{i + 1}</span>)}</div></div><Icon name="arrow" size={30}/><div><span className="mini-label">This transaction's segment</span><div className="page-grid changed-pages">{[2, 5, 9].map(n => <span className="changed" key={n}>p{n}</span>)}</div><small>Only final images of changed pages</small></div></div>
      <Detail title="The WAL capture algorithm"><p>Read the 32-byte WAL header and 24-byte frame headers. A salt change or restarted file resets the cursor. Accumulate page images until a commit-size marker appears; keep the final image for each page number. Ignore uncommitted trailing frames and pages beyond the committed database size. Capture advances the offset only through committed data.</p></Detail>
      <Detail title="What is in a .ltx segment?"><p>The custom binary codec starts with <code>STXLTX01</code>, then epoch, txid, page size, final database page count, and changed-page count. Each page entry has its number and bytes. CRC32 detects accidental corruption; it is not a cryptographic authenticity guarantee. Replay writes pages at their file offsets, resizes the database to its final page count, and syncs it.</p></Detail>
      <Source files="crates/ltx/src/lib.rs:18-194"/>
    </Section>
    <Section eyebrow="Recovery is selective" title="Newest usable epoch. Newest snapshot. No gaps."><RestoreLab/></Section>
    <Section eyebrow="Keep recovery bounded" title="Compaction trades many deltas for one image.">
      <Flow nodes={[{ title: "64 segments", text: "Default snapshot interval" }, { title: "TRUNCATE checkpoint", text: "Fold WAL into SQLite" }, { title: "Stream snapshot", text: "Hold actor slot lock", tone: "mint" }, { title: "Garbage collect", text: "Delete superseded history" }]}/>
      <div className="grid two"><Card title="Publish before deleting" icon="shield"><p>After the new snapshot is durable, delete older epochs, older snapshots in the current epoch, and segments at or below the snapshot txid. Never treat these objects as an indefinite audit log or a built-in point-in-time backup history.</p></Card><Card title="Stream, do not buffer the whole DB" icon="database"><p>Azure file uploads use 8 MiB blocks followed by a block-list commit. Downloads use 8 MiB range reads pinned to one ETag. The slot lock keeps the checkpointed database file stable through upload.</p></Card></div>
      <Note title="Compaction failures do not erase the already uploaded transaction">Compaction happens after the acknowledgement gate and can outlive the response. Upload/GC failures log warnings and may leave redundant objects. A checkpoint failure drops the actor. The durable segment chain remains the recovery path when no newer usable snapshot was published.</Note>
      <Source files="crates/node/src/actor.rs:204-261; crates/node/src/node.rs:480-510; crates/store/src/azure.rs"/>
    </Section>
    <Section eyebrow="Bucket anatomy" title="The namespace tells the story.">
      <Code title="Illustrative object-store keys">{`fleet/peer-auth.json\nnodes/node-a.json\ndeploy/demo.hello/current.json\ndeploy/demo.hello/<content-id>/component.wasm\ndeploy/demo.hello/<content-id>/manifest.json\nactors/demo.hello/counter/alice/owner.json\nactors/demo.hello/counter/alice/ltx/e0000000008/\n  snapshot-0000000000000042.db\n  0000000000000043.ltx\n  0000000000000044.ltx`}</Code>
      <p><code>demo/hello</code> becomes <code>demo.hello</code> in storage. App segments cannot contain dots, so this mapping does not collide with a literal dotted app name. Epoch and transaction numbers are distinct: an activation increments the epoch; a committed page-producing transaction increments txid.</p>
      <Table headers={["Store operation", "Protocol use"]} rows={[["get / get_range / list", "Read leases, ownership, code and restore objects; enumerate consistent history."], ["put_if_absent", "Create a missing lease, owner record, or deployment pointer."], ["put_if_match(etag)", "Renew, acquire, release, delete logically, or publish only if the observed version still matches."], ["put / put_file", "Publish segment bytes or a streamed snapshot."], ["get_to_file", "Restore a snapshot without keeping the whole image in memory."], ["delete", "Remove data superseded by a durable snapshot or attempt cleanup after actor deletion."]]}/>
      <Note title="Run the conformance probe, but know its scope" tone="amber"><code>statex diagnose</code> checks conditional create/update, stale-version rejection, ranged reads, and list-after-write. Passing a small probe is necessary evidence of store behavior, not an exhaustive distributed consistency or durability proof.</Note>
      <Source files="crates/node/src/layout.rs; crates/store/src/lib.rs:1-66, 113-149"/>
    </Section>
  </>;
}

export function Runtime() {
  return <>
    <div className="sandbox"><div className="sandbox-header"><Icon name="shield"/><span>WASMTIME COMPONENT SANDBOX</span><Badge>one instance per resident actor</Badge></div><div className="sandbox-core"><Icon name="cube" size={38}/><div><h3>Your actor implementation</h3><p>Rust or Python → WASI p2 component → exported WIT methods</p></div></div><div className="sandbox-ports">{[["context", "Identity + epoch"], ["sql", "Private SQLite"], ["http-client", "Allowed hosts"], ["log", "Node logs"], ["actors", "Typed calls"]].map(([name, desc]) => <div key={name}><span className="port-dot"/><strong>{name}</strong><small>{desc}</small></div>)}</div><div className="sandbox-floor">No preopened directories · no inherited environment · no granted raw sockets</div></div>
    <Section eyebrow="Useful doors" title="Every host capability has a boundary.">
      <Table headers={["Import", "What the guest can do", "Boundary / detail"]} rows={[["context", "Read app, actor type, key, epoch.", "Use identity to address your entity; epoch is not a business version."], ["sql", "Execute statements; query rows and typed values.", "The host owns transaction control. BEGIN, COMMIT, SAVEPOINT, ATTACH, VACUUM, PRAGMA and related controls are rejected."], ["http-client", "Send HTTP(S) through the host.", "Host allowlist is explicit; side effects are not transactional. Response body cap is 10 MiB."], ["log", "Emit structured-level messages to node logs.", "Logs are observability, not a durable application ledger."], ["actors / generated client imports", "Call another actor with typed arguments.", "Calls go through the node; callee commits independently and can return transport/runtime call-error."], ["WASI p2", "Use the configured component runtime facilities.", "No automatic grant of local directories, environment, or raw socket access; stdout/stderr go to node logs."]]}/>
      <div className="metrics three"><div><strong>5,000 ms</strong><span>default method timeout</span></div><div><strong>64 MiB</strong><span>default guest memory limit</span></div><div><strong>10 ms</strong><span>engine epoch tick</span></div></div>
      <Note title="Execution limits are not an end-to-end API latency bound">Wasmtime epoch interruption bounds guest execution; slot waiting, activation, store I/O, forwarding, and host calls have their own timing behavior. A long queue or cold restore is not included in a simple “5 seconds per HTTP request” promise.</Note>
      <Source files="crates/runtime/src/lib.rs:22-45, 95-174, 229-238; crates/runtime/src/host.rs:72-181; wit/statex-host.wit"/>
    </Section>
    <Section eyebrow="The contract is executable" title="WIT is the common language.">
      <div className="grid two"><Code title="Illustrative actor interface">{`package demo:hello;\n\ninterface counter {\n  increment: func(by: s64) -> s64;\n  get: func() -> s64;\n}\n\nworld app {\n  import statex:host/sql;\n  export counter;\n}`}</Code><div><h3>From interface to invocation</h3><p>Each named exported interface becomes an actor type. Its functions become callable methods. The manifest holds this schema alongside migrations, HTTP policy, memory/time limits, and typed call imports.</p><p>Top-level world functions and resource-based actor interfaces are not supported. Other component toolchains can work if they emit the supported WASI p2 component and WIT surface.</p><Badge>NO MANUAL ROUTE REGISTRATION</Badge></div></div>
      <Table headers={["WIT shape", "JSON representation", "Important detail"]} rows={[["record", "{\"display-name\": \"Ada\"}", "Input lookup also accepts snake_case and camelCase spellings."], ["option<T>", "null or a T value", "Omitted optional fields/arguments can map to none."], ["enum", "\"ready\"", "Variant names are strings."], ["variant", "{\"tag\": \"ready\", \"value\": ...}", "A payload-free variant can also be supplied as a bare tag string."], ["list<u8>", "Base64 string", "Other lists are JSON arrays."], ["s64 / u64", "JSON number or numeric string on input", "Use strings where JavaScript integer precision would be lost."], ["nested result<T,E>", "{\"ok\": ...} or {\"err\": ...}", "Top-level method result is separately unwrapped into HTTP 200 or 422."], ["function arguments", "{\"by\": 1} or [1]", "No-argument calls can have an empty body; names and order come from WIT."]]}/>
      <Source files="crates/runtime/src/manifest.rs:159-223, 329-418; crates/runtime/src/json.rs"/>
    </Section>
    <Section eyebrow="Actors can call actors" title="Typed calls. Separate transactions.">
      <Flow label="Nested actor call with independent commits" nodes={[{ title: "Actor A", text: "Transaction + slot held" }, { title: "Client import", text: "Key first; WIT → JSON" }, { title: "NodeCaller", text: "Local invoke or forward" }, { title: "Actor B", text: "Own commit + durability", tone: "mint" }, { title: "A resumes", text: "Can still roll back", tone: "amber" }]}/>
      <div className="grid two"><Code title="Two layers of result / conceptual type">{`result<\n  result<receipt, payment-error>,\n  statex:host/actors.call-error\n>\n\nouter error = transport / runtime / routing\ninner error = callee's business result`}</Code><div><h3>Why the chain travels with the call</h3><p>The caller adds itself to the chain. The node rejects a target already on that chain, or a chain with 16 entries, with <code>508 cycle</code>. Waiting is bounded by the caller's remaining deadline.</p><p>Two independent chains can still wait on each other's locks: A → B and B → A. That case is not detected by the per-chain check; timeout breaks the wait.</p></div></div>
      <Note title="A callee's commit cannot be rolled back by its caller" tone="amber">If B succeeds, then A traps, B's state remains. A callee timeout/unavailable is also an unknown outcome. Retrying safely requires stable step IDs or idempotency keys in the callee, not just a catch-and-retry loop in A.</Note>
      <Detail title="HTTP policy and external side effects"><p>The host allowlist accepts exact hosts, wildcard subdomains such as <code>*.example.com</code>, or <code>*</code>. It is host-based, not method/path-based. The default HTTP adapter disables redirects and bounds response size; replacement transports must honor admission and deadlines. Do not equate an allowlist with a complete network-isolation policy. Keep the list narrow and treat each request as an external effect that may survive an actor rollback. A durable intent table plus an external relay is an application design, not a built-in atomic HTTP feature.</p></Detail>
      <Detail title="Instance reuse is not state rollback"><p>The actor keeps its Wasmtime instance between calls. A trap drops the instance, and switching app code resets it. SQLite rollback does not rewind arbitrary guest memory. Prefer SQLite for durable or transaction-sensitive state rather than in-memory counters.</p></Detail>
      <Source files="crates/runtime/src/calls.rs:91-162; crates/node/src/node.rs:138-160, 349-362; crates/node/src/actor.rs:146-202"/>
    </Section>
  </>;
}

const failureRows = [
  ["Owner crashes", "Old node stops responding; its stored lease may still look alive.", "Wait for lease expiry, CAS a new epoch, restore, activate.", "Acknowledged writes survive under the documented assumptions; requests in flight have uncertain outcomes."],
  ["Node loses store access", "Renewal/upload/owner reads can fail.", "Local lease validity closes; renewal loop fences; writes cannot pass the full acknowledgement path.", "A failed store request may have applied remotely. Treat upload/ack failure as unknown."],
  ["Node cannot reach owner", "Forwarding transport fails while owner may still be healthy.", "Retry routing; do not take over a matching live session.", "Reachability from one node is not ownership permission."],
  ["Two takeover attempts", "Both readers observe the same old ETag.", "One conditional write wins; the loser re-reads.", "Only the winner proceeds with that acquired record."],
  ["Stale actor owner", "Lease/owner identity no longer matches.", "No write acknowledgement; discard local actor.", "Old-epoch objects do not replace the newer snapshot epoch."],
  ["Guest method err / trap", "Domain error, panic, deadline interruption, or guest memory exhaustion.", "Rollback local SQL; method err is 422, trap is 500; trap resets instance.", "External HTTP and independently committed callees are not rolled back."],
  ["Restore object missing or corrupt", "A listed snapshot/segment disappears, or segment decoding fails.", "Activation fails; routing retries may eventually surface 503.", "Do not silently fabricate a successful actor restore."],
  ["Compaction upload/GC fails", "A snapshot task logs failure after the write gate.", "Keep durable history; retry compaction on later writes as applicable.", "The write reply is not a guarantee that compaction or old-object deletion finished."],
  ["Reply lost", "Server completed, but the client did not receive the response.", "Client retries by stable request ID and reads the stored result.", "Exactly-once client observation is not built in."],
  ["New deployment fails to load", "Refresh loop logs an error.", "The node retains previously loaded app state until a successful refresh.", "Deployment visibility is polled, not an atomic fleet-wide code switch."]
];

export function Failures() {
  const [filter, setFilter] = useState("");
  const rows = failureRows.filter(r => r.join(" ").toLowerCase().includes(filter.toLowerCase()));
  return <>
    <FailureLab/>
    <Section eyebrow="Design for ambiguity" title="Unknown is a real outcome, not an error synonym.">
      <div className="grid three"><Card title="Committed?" icon="database"><p>Did SQLite commit on the current node? That alone says nothing about surviving the loss of local disk.</p></Card><Card title="Durable?" icon="layers"><p>Did the segment reach the store? It might have, even if the upload response or later ownership read failed.</p></Card><Card title="Observed?" icon="check"><p>Did the client receive success? A reply can be lost after all server-side work completed.</p></Card></div>
      <Code title="Application-level idempotency / illustrative SQL and protocol">{`CREATE TABLE requests (\n  request_id TEXT PRIMARY KEY,\n  result_json TEXT NOT NULL\n);\n\n# In the SAME actor call transaction:\n# 1. If request_id exists, return the recorded result.\n# 2. Apply the business mutation.\n# 3. Insert request_id + the exact result to return.\n# The host commits and replicates both together.`}</Code>
      <p>Choose keys at the logical-operation level, keep them stable across retries, define a retention policy, and bind them to the expected operation/payload so the same key cannot accidentally refer to different work. A uniqueness constraint prevents duplicate local application; an external service needs its own matching protection.</p>
      <Note title="The Python client already retries by default" tone="amber">The transport defaults to 3 retries (up to 4 attempts), with exponential backoff starting at 0.2 seconds. It retries an HTTP error whose code is <code>unavailable</code> and URL/network errors; it does not inspect whether the method is idempotent. A non-idempotent increment can therefore be repeated without an explicit retry loop in your application.</Note>
      <Source files="sdk/python/statex_client/_runtime.py:55-89"/>
    </Section>
    <Section eyebrow="Failure matrix" title="What breaks, what reacts, what remains.">
      <label className="search-field"><Icon name="search" size={18}/><input aria-label="Filter failure conditions" placeholder="Filter failures, e.g. owner, store, deployment..." value={filter} onChange={e => setFilter(e.target.value)}/></label>
      <Table headers={["Failure condition", "What happens", "Engine response", "Application meaning"]} rows={rows}/>
      {!rows.length && <p role="status">No matching failure conditions. Clear the filter to see all cases.</p>}
      <Source files="docs/guarantees.md; crates/node/src/{node,lease,actor,lib}.rs"/>
    </Section>
    <Section eyebrow="Know the response" title="A compact error contract."><Table headers={["HTTP", "Code / outcome", "Meaning", "Response strategy"]} rows={errors}/></Section>
    <Section eyebrow="Timing and availability" title="Failover is not a zero-downtime promise.">
      <div className="grid two"><Card title="Lease waiting" icon="clock"><p>Default TTL is 10 seconds. Immediately after a crash, a still-live-looking owner may be unreachable. Takeover eligibility follows lease expiry; cold restore adds more time.</p></Card><Card title="Retry budget is not a stopwatch" icon="branch"><p>The routing loop permits retries for roughly 2 × TTL, sleeping 250 ms between attempts. A forwarded HTTP call itself has a 60-second client timeout; an in-flight attempt is not cut off at the retry-loop deadline.</p></Card></div>
      <Note title="Do not promise a universal 20-second response ceiling" tone="amber">The 2 × TTL value controls whether another retry is scheduled, not an absolute end-to-end deadline. Lock acquisition, component work, and storage/network I/O can extend latency. Actor-to-actor callers separately bound their wait by the caller's remaining deadline.</Note>
      <Source files="crates/node/src/node.rs:214-216, 309-325, 544-563; docs/guarantees.md"/>
    </Section>
  </>;
}

export function Development() {
  return <>
    <Flow nodes={[{ title: "Define", text: "WIT + migrations" }, { title: "Implement", text: "Rust / Python" }, { title: "Verify", text: "Schema + sandbox" }, { title: "Publish", text: "Objects + CAS", tone: "mint" }, { title: "Adopt", text: "Poll, next call" }]}/>
    <Section eyebrow="Authoring surfaces" title="A small set of files defines an app.">
      <div className="grid two"><Code title="Typical workspace app">{`apps/demo/hello/\n  statex.toml\n  wit/app.wit\n  wit/deps/                 # host + client contracts\n  migrations/counter/\n    0001_init.sql\n    0002_add_history.sql\n  src/lib.rs               # Rust implementation\n  # or app.py for a Python app`}</Code><div><Table headers={["File", "Purpose"]} rows={[["statex.toml", "App identity, component build metadata, limits, HTTP policy and calls."], ["wit/app.wit", "Typed imported capabilities and exported actor APIs."], ["migrations/<type>/*.sql", "Ordered schema history for that actor type."], ["Implementation", "Business methods using host SQL, typed actors, logging and HTTP."], ["Generated bindings", "Client interfaces and language-specific wrappers, derived from WIT."]]}/></div></div>
      <Code title="Standalone workflow / commands to run yourself">{`export STATEX_GUEST_PATH=/path/to/statex/crates/guest\nstatex new hello                  # standalone Rust app\n# statex new --lang python hello\ncd hello\ncargo test                        # native guest tests (Rust)\nstatex dev                        # local node + rebuild loop\nstatex call counter alice increment -a by=2\nstatex codegen python              # typed external client\nstatex check\nstatex diagnose                   # configured store conformance\nstatex deploy                     # verify, upload, publish\n# Optional workspaces support check --all and registry build.`}</Code>
      <p>These commands describe the repository workflow; this guide does not execute them. For Python guest applications, the CLI builds components with componentize-py and supports native test stubs via <code>statex test</code>. Any additional tools should be installed through your approved development process.</p>
      <Source files="README.md; docs/developer-guide.md; crates/cli/src/{scaffold,project,python,codegen}.rs"/>
    </Section>
    <Section eyebrow="Publish code without rebuilding the fleet" title="The pointer is the deployment switch.">
      <Flow nodes={[{ title: "Build & verify", text: "Instantiate with migrated DBs" }, { title: "Upload content", text: "component.wasm + manifest" }, { title: "Compare & CAS", text: "current.json version", tone: "mint" }, { title: "Node polls", text: "2-second default" }, { title: "Next actor call", text: "New instance + lazy migration" }]}/>
      <div className="grid two"><Card title="Compatibility is part of publishing" icon="shield"><p>The deploy path compares the new manifest to the deployed one inside the current-pointer CAS loop. It checks typed calls against deployed callees and checks existing callers against a changed callee. The same content ID is idempotent.</p></Card><Card title="The switch is lazy, not global" icon="clock"><p>Nodes refresh app code independently. A resident actor notices a new code pointer on its next call, drops its old instance, and rechecks migrations. There is no fleet-wide stop-the-world cutover or guarantee every actor runs the same version simultaneously.</p></Card></div>
      <Note title="Escape hatches are explicit" tone="amber"><code>--allow-breaking</code> can bypass compatibility refusal. <code>--allow-unresolved-calls</code> can permit unresolved or mismatched callees. Neither flag makes an incompatible protocol safe; coordinate changes and regenerations deliberately.</Note>
      <Detail title="Content identity and verification"><p>The deployment content ID derives from the component hash plus serialized manifest, so a manifest change is significant even with the same Wasm. Nodes verify the fetched component SHA256 against the deployment pointer and manifest. A new pointer increments the deployment version; that number is separate from actor epochs and txids.</p></Detail>
      <Source files="crates/node/src/deploy.rs:93-149, 192-215; crates/node/src/node.rs:271-290; crates/node/src/actor.rs:146-152"/>
    </Section>
    <Section eyebrow="Schema evolves with a call" title="Migrations are transactional and append-only.">
      <Flow nodes={[{ title: "Old actor schema", text: "Previous migration set" }, { title: "BEGIN IMMEDIATE", text: "First call on new code" }, { title: "Pending migrations", text: "_statex_migrations" }, { title: "Method + COMMIT", text: "Same transaction", tone: "mint" }, { title: "Same durable segment", text: "Schema + business changes" }]}/>
      <p>A failed first method also rolls back its pending migrations; they are retried on a later successful call. Explicit <code>_create</code> uses a touch operation to apply migrations without running a business method. Never rewrite, reorder, or remove applied migration history; add a new SQL file.</p>
      <Note title="Deploy authorization lives outside StateX" tone="amber">Anyone with write access to the deployment namespace can publish code. Restrict <code>deploy/</code> writes to authorized CI; nodes need read access there plus the appropriate coordination/data permissions elsewhere. Peer HMAC is not deploy or end-user access control.</Note>
    </Section>
    <Section eyebrow="Typed clients in both directions" title="One schema, two kinds of caller.">
      <div className="grid two"><Card title="An external caller" icon="code"><p><code>statex codegen python</code> produces a typed client with a stdlib HTTP runtime. It addresses actors through the public API of any node and maps JSON values into generated language types.</p></Card><Card title="Another actor" icon="branch"><p><code>statex calls sync</code> generates client WIT under <code>wit/deps/</code> and Rust call shims. Methods take the target key first; the runtime dynamically links these imports to NodeCaller.</p></Card></div>
      <Detail title="What to test at each layer"><p>Guest-native tests check business SQL and error handling with a mock host and per-key state. Stub outgoing actor calls explicitly. Runtime tests cover component instantiation, WIT mapping, policy and limits. Cluster tests cover forwarding, graceful handoff, crash recovery, fencing, compaction and deploy compatibility. The e2e script exercises built components, clients, actor calls and workspace checks.</p></Detail>
      <Detail title="Native tests are useful, but not a simulated cluster"><p>The Rust test host gives each (actor type, key) its own in-memory SQLite database. <code>testing::call</code> wraps a closure in a transaction and rolls back on panic; <code>testing::try_call</code> also rolls back on Err. <code>mock_http</code> installs an HTTP handler, generated client <code>stub(...)</code> functions stand in for actor callees, and unstubbed calls panic. These tests validate business logic but do not exercise object-store durability or real network forwarding.</p></Detail>
      <Source files="crates/cli/src/calls.rs; crates/guest/src/testing.rs; sdk/python-guest/statex_testing.py; crates/node/tests/cluster.rs; scripts/e2e.sh"/>
    </Section>
  </>;
}

const useCases = [
  { title: "Counters & account state", kind: "Repository example", icon: "database", key: "counter/alice · account/alice", text: "A small entity has multiple related updates and a natural key. Serialize increments, balances, or history in its own database.", boundary: "One account call is atomic. A transfer between two account actors is not automatically a transaction.", source: "examples/counter/src/lib.rs; examples/python-counter" },
  { title: "Configuration & key/value", kind: "Repository example", icon: "layers", key: "kv/defaults · config/checkout", text: "Use per-key durable state and typed cross-app calls. The demo configuration and Rust counter apps interact with the demo database app.", boundary: "A config read through another actor is a separate call, not a shared SQLite connection or cross-app SQL join.", source: "apps/demo/config; apps/demo/db; apps/demo/rustdemo/src/lib.rs" },
  { title: "Relay / typed composition", kind: "Repository example", icon: "branch", key: "relay/checkout", text: "A relay actor calls counters, accounts, or other relay actors through generated typed interfaces. This demonstrates composition and failure mapping.", boundary: "The relay's local record can roll back while a called counter or account already committed.", source: "examples/caller; examples/python-caller" },
  { title: "Shopping cart", kind: "Application design", icon: "cube", key: "cart/customer-204", text: "Keep line items, coupon decisions, and the cart version together. A call can atomically modify several local tables before replying.", boundary: "Inventory reservations and payment authorization need idempotent cross-actor/external protocols.", source: "Derived from the per-actor transaction model" },
  { title: "Session or conversation", kind: "Application design", icon: "book", key: "conversation/session-73", text: "Persist messages, workflow state, preferences, and request deduplication for an individual session. Different sessions can progress independently.", boundary: "An idle actor is evicted. Durable data survives, but sockets, streams and in-memory continuations do not.", source: "Derived from activation and idle-eviction behavior" },
  { title: "Reservations & quotas", kind: "Application design", icon: "shield", key: "quota/tenant-5 · room/204", text: "Enforce an invariant within one chosen key: reserve a slot only if capacity remains, or debit a quota with the request ledger in the same transaction.", boundary: "A hot global quota key is a serialized bottleneck. Sharding changes the invariant and requires a reconciliation protocol.", source: "Derived from serialized actor calls + SQLite" }
];

export function UseCases() {
  const [mode, setMode] = useState("all");
  const cases = useCases.filter(c => mode === "all" || (mode === "examples" ? c.kind === "Repository example" : c.kind === "Application design"));
  return <>
    <div className="filter-bar"><span className="mini-label">Explore the fit</span><div className="segmented" aria-label="Use case category">{[["all", "All use cases"], ["examples", "In this repository"], ["designs", "Design ideas"]].map(([id, label]) => <button key={id} aria-pressed={mode === id} onClick={() => setMode(id)}>{label}</button>)}</div></div>
    <div className="grid two use-case-grid">{cases.map(c => <article className="use-case card" key={c.title}><div className="use-case-top"><Icon name={c.icon} size={26}/><Badge tone={c.kind === "Repository example" ? "green" : "amber"}>{c.kind}</Badge></div><h2>{c.title}</h2><code className="actor-key">{c.key}</code><p>{c.text}</p><div className="boundary"><span className="mini-label">Mind the boundary</span><p>{c.boundary}</p></div><Source files={c.source}/></article>)}</div>
    <Section eyebrow="Choose the grain" title="The actor key is a correctness decision.">
      <Flow nodes={[{ title: "Identify an invariant", text: "What must change atomically?" }, { title: "Pick a key", text: "Keep that data together" }, { title: "Estimate contention", text: "One serialized call lane" }, { title: "Plan outside effects", text: "Retries, IDs, compensation", tone: "mint" }]}/>
      <Table headers={["Good fit", "Reconsider or add another system"]} rows={[["Many independent entities with bounded local transactions.", "One global, heavily contended mutable entity."], ["Per-entity SQL queries and schema evolution.", "Cross-actor SQL joins and analytical scans."], ["State that may go cold and reactivate on a request.", "Hard real-time execution or guaranteed sub-millisecond writes."], ["Idempotent business methods and explicit protocols.", "Assuming every retry executes exactly once."], ["Application-managed durable workflows.", "Expecting built-in cron, queue delivery, or long-running agent execution."]]}/>
      <Note title="Scale out across keys, not through a key">Every durable write has object-store work on its critical path. Cold activation downloads and replays state. Large snapshots hold the actor lock while streaming. Measure with your entity sizes and store latency before treating this as a throughput or latency guarantee.</Note>
      <ChapterLink id="patterns">Build agents, queues and schedules on the same model</ChapterLink>
    </Section>
  </>;
}

export function Patterns() {
  return <>
    <Note title="This chapter is a design guide, not a feature announcement" tone="amber">The repository implements the common actor, SQL, alarm, lease, and durability machinery. The agent, queue, cron, and workflow systems below are application patterns you could build with it. There are no built-in consumer, outbox-dispatcher, or background-agent APIs.</Note>
    <Section eyebrow="The reusable shape" title="State machine + driver + safe retries.">
      <div className="pattern-formula"><div><Icon name="clock"/><strong>External driver</strong><small>A tick, event, consumer, or worker</small></div><Icon name="arrow"/><div className="mint"><Icon name="cube"/><strong>StateX actor</strong><small>Serialize → mutate → commit → replicate</small></div><Icon name="arrow"/><div><Icon name="branch"/><strong>External effect</strong><small>Idempotent delivery + completion token</small></div></div>
      <p>The durable unit is a state transition, not an endless process. Make one short actor call record the next state or intent. Let a driver perform work and submit its result. After crashes, recover the ledger and retry unfinished steps rather than hoping a suspended stack resumes.</p>
    </Section>
    <PatternLab/>
    <Section eyebrow="Do not conflate the leases" title="Engine ownership and job claims protect different things.">
      <Table headers={["Concept", "StateX node lease", "Application claim / run token"]} rows={[["Protects", "Which node session may own and acknowledge actor writes.", "Which worker may complete a job or step."], ["Stored in", "nodes/<id>.json, referenced by owner.json.", "Application tables in the actor's SQLite database."], ["Renewed by", "Node renewal loop.", "Application worker/driver protocol."], ["Expiry permits", "An ownership CAS when peers see the lease expired.", "A retry or reclaim according to application rules."], ["Does not do", "Deliver a job, schedule a timer, or cancel an external tool.", "Prevent a stale worker from affecting an unfenced external system."]]}/>
      <Note title="A durable intent table is only half an outbox">The table makes the intention recoverable. A separately operated relay must discover it, retry delivery, record completion, and reconcile ambiguity. The recipient must deduplicate or fence effects. StateX's successful actor write does not make the external delivery exactly once.</Note>
    </Section>
    <Section eyebrow="A reusable checklist" title="Before shipping any of these patterns.">
      <div className="grid three"><Card title="Identity" icon="cube"><p>Actor key, operation ID, claim/step token, and occurrence ID must represent distinct concepts. Reuse the operation ID across retries, not a freshly generated value.</p></Card><Card title="Recovery" icon="layers"><p>Define who scans incomplete work, how often, and what happens after callback loss. Store enough result data to return the same answer to duplicates.</p></Card><Card title="Boundedness" icon="clock"><p>Bound step execution, scans, catch-up batches, retained deduplication records, and external retries. Define poison-message and compensation policies.</p></Card></div>
      <Source files="Designs derived from docs/guarantees.md; crates/node/src/actor.rs; wit/statex-host.wit (available host capabilities)"/>
    </Section>
  </>;
}

const glossary = [
  ["Actor", "A logical (app, type, key) identity with its own private SQLite database."],
  ["Actor type", "A named exported WIT interface whose functions are methods."],
  ["Activation", "Acquiring ownership, restoring/opening SQLite, and publishing a new-epoch snapshot before serving."],
  ["App", "One deployed component plus its WIT-derived manifest, migrations and policies."],
  ["CAS", "Compare-and-swap: conditional overwrite only if the observed object ETag still matches."],
  ["Epoch", "A monotonically increasing actor activation number. Separates data prefixes for different ownership incarnations."],
  ["ETag", "An opaque store object version. Used for conditional writes; not the actor epoch or transaction ID."],
  ["Fencing", "Withdrawing a process's authority to acknowledge writes after its lease is invalid or replaced."],
  ["Idempotency key", "An application-defined operation identity persisted with the result to deduplicate retries."],
  ["Lease margin", "max(TTL/5, 200 ms). The owner stops considering its lease valid before peers consider it expired."],
  ["LTX-style segment", "StateX's checksummed STXLTX01 encoding of changed database pages for a committed txid."],
  ["Manifest", "The app's extracted type schema, code hash, migrations, HTTP policy, limits and call contracts."],
  ["Node lease", "A store record identifying a node session, advertised internal address and expiry."],
  ["Owner record", "The actor record holding state, node, session and epoch, retained through release and deletion."],
  ["Resident actor", "A currently loaded actor with a local SQLite replica, WAL cursor and optional Wasmtime instance."],
  ["Session", "A random identifier per node process start. Reusing a node ID does not reuse a process session."],
  ["Slot", "An in-memory actor entry protected by an async mutex; not a durable queue."],
  ["Snapshot", "A complete checkpointed SQLite database image at a particular transaction ID."],
  ["Tombstone", "An owner record marked deleted; data may be cleaned up but the epoch history is retained."],
  ["Transaction ID / txid", "The monotonically advancing durable page-log position, incremented for a committed captured page set."],
  ["Unknown outcome", "The client cannot determine whether an operation applied; an error or lost reply may coexist with durable state."],
  ["WAL", "SQLite's write-ahead log. StateX captures committed frames and disables automatic checkpointing."],
  ["WIT", "WebAssembly Interface Types: the typed contract that defines host imports and actor methods."],
  ["Working tree", "The local source files as inspected, including uncommitted changes. This guide is not tied to a released version."]
];

export function Reference() {
  const [query, setQuery] = useState("");
  const terms = glossary.filter(t => t.join(" ").toLowerCase().includes(query.toLowerCase()));
  return <>
    <Note title="Scope: default implementations">SQLite/WAL diagrams describe the default backend. Custom implementations follow the contracts in <code>docs/extensions/</code>; namespaced application examples are optional, not a team layout requirement. Source references identify files and selected line ranges; line numbers may move as code evolves. Interactive labs are deterministic explanatory models, not calls to a real cluster.</Note>
    <Section eyebrow="Operational defaults" title="Numbers have scope.">
      <Table headers={["Setting", "Default / value", "Scope"]} rows={[["Node lease TTL", "10 s", "Peer liveness and local acknowledgement eligibility."], ["Renewal cadence", "TTL / 3", "Normal renewal-loop sleep."], ["Lease safety margin", "max(TTL / 5, 200 ms)", "Local valid() cutoff before stored expiry."], ["Idle timeout", "300 s", "Eligible idle actors are released by a periodic scanner."], ["Idle scan cadence", "clamp(idle / 4, 100 ms, 30 s)", "Eviction is not instantaneous at exactly the idle threshold."], ["Deployment polling", "2 s", "Per-node app refresh."], ["Snapshot interval", "64 segments", "Compaction threshold in durable page-producing transactions."], ["Guest timeout", "5,000 ms", "Default runtime execution limit, not end-to-end HTTP latency."], ["Guest memory", "64 MiB", "Wasmtime store limit for each actor instance."], ["Maximum forwarding hops", "4", "Internal node-to-node route loop guard."], ["Maximum actor call-chain entries", "16", "Per-chain re-entry/depth guard."], ["Routing retry window", "2 × TTL; 250 ms retry sleep", "Eligibility to start another attempt; not a hard deadline."], ["Peer HTTP client timeout", "60 s", "An individual forwarded request."], ["Peer timestamp tolerance", "60 s absolute difference", "Reject stale signed internal requests."], ["Python transport retries", "3 retries, 0.2 × 2^attempt backoff", "Up to 4 attempts; unavailable and URL errors, regardless of idempotency."], ["Actor key", "1–512 bytes", "Percent-encoded as one route segment; length is bytes."], ["Azure snapshot chunks", "8 MiB", "Block uploads and pinned ranged downloads."], ["Outbound HTTP body cap", "10 MiB", "Host response-body limit."], ["SQLite", "WAL, FULL sync, autocheckpoint=0", "Host controls checkpointing and transaction boundaries."]]}/>
      <Source files="crates/node/src/node.rs:29-67, 309-325, 568-580; crates/node/src/lease.rs; crates/node/src/lib.rs:123-137; crates/node/src/layout.rs:21; crates/runtime/src/{lib,manifest,host}.rs; crates/store/src/azure.rs"/>
    </Section>
    <Section eyebrow="Addressing" title="A compact public API.">
      <Table headers={["Verb", "Route", "Purpose"]} rows={[["POST", "/v1/apps/<app>/actors/<type>/<key>/<method>", "Invoke a WIT method; lazily create actor on first use."], ["POST", "/v1/apps/<app>/actors/<type>/<key>/_create", "Explicit creation; 409 if a non-deleted actor exists."], ["DELETE", "/v1/apps/<app>/actors/<type>/<key>", "Mark deleted and attempt state cleanup."], ["GET", "/v1/apps", "List node-loaded apps."], ["GET", "/v1/apps/<app>/schema", "Return the loaded app manifest."], ["GET", "/v1/apps/<app>/actors?type=&limit=", "List actor ownership records; default limit 100."], ["GET", "/healthz", "JSON including ok, fenced, identity, apps, resident actors."], ["POST", "/internal/v1/invoke", "Peer-only signed forwarding payload, not the public caller API."]]}/>
      <p>Apps are <code>app</code> or <code>team/app</code>. App path segments use lowercase letters, digits and dashes; <code>actors</code> and <code>schema</code> cannot be app segments. App naming also reserves host/runtime package identities. Method/type snake_case is normalized to WIT kebab-case. Encode a slash inside an actor key as <code>%2F</code>, not a new route segment.</p>
      <Note title="Health JSON needs to be inspected" tone="amber">The health handler returns a JSON object with <code>ok: lease.valid()</code>; it does not switch to a failing HTTP status when that boolean is false. A status-only probe is not sufficient to infer that a node can acknowledge work.</Note>
      <Source files="crates/node/src/api.rs:36-165; crates/node/src/layout.rs; crates/runtime/src/manifest.rs:229-268"/>
    </Section>
    <Section eyebrow="Source trail" title="Where to go one level deeper.">
      <Table headers={["Concern", "Files / entry points"]} rows={[["Cluster lifecycle", "crates/node/src/lib.rs — start, shutdown, kill, background loops."], ["Routing and ack gate", "crates/node/src/node.rs — invoke, try_invoke, run, forward, invoke_forwarded."], ["Ownership protocol", "crates/node/src/owner.rs — acquire, release, still_owner."], ["Lease protocol", "crates/node/src/lease.rs — acquire, valid, renew_once, run, release."], ["Actor lifecycle", "crates/node/src/actor.rs — activate, execute, run_in_tx, snapshot, compact, gc."], ["Page-log codec and restore", "crates/ltx/src/lib.rs — WalTail::capture, Segment, apply_segment, plan_restore."], ["Store contracts", "crates/store/src/lib.rs; local.rs; azure.rs — ObjectStore and conformance_test."], ["Runtime and host imports", "crates/runtime/src/lib.rs; host.rs; calls.rs; json.rs; manifest.rs; compat.rs."], ["Deployment", "crates/node/src/deploy.rs — unresolved_calls, broken_callers, deploy, fetch."], ["Guest and client developer surfaces", "wit/statex-host.wit; crates/guest; sdk/python-guest; sdk/python; crates/cli."], ["Cluster behavior tests", "crates/node/tests/cluster.rs — forwarding, crash_takeover_keeps_acked_writes, stale_owner_is_fenced, ack_requires_current_ownership, compaction_and_restore, call_cycles_are_rejected_not_deadlocked."], ["Narrative docs", "README.md; docs/architecture.md; docs/guarantees.md; docs/developer-guide.md."]]}/>
    </Section>
    <Section eyebrow="Glossary" title="Shared words, precise meanings.">
      <label className="search-field"><Icon name="search" size={18}/><input aria-label="Search glossary" placeholder="Find a term: epoch, lease, actor, WAL..." value={query} onChange={e => setQuery(e.target.value)}/></label>
      <dl className="glossary">{terms.map(([term, definition]) => <div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl>
      {!terms.length && <p role="status">No matching terms. Try a shorter query.</p>}
    </Section>
    <Section eyebrow="Assumptions and non-guarantees" title="Keep the model honest.">
      <div className="grid two"><Card title="Required foundations" icon="shield" tone="mint"><p>Correct conditional create/overwrite, read-after-write and list consistency, trustworthy store persistence, aligned clocks within the lease margin, properly restricted deployment writes, and a supervisor for production node fencing.</p></Card><Card title="Not supplied by this protocol" icon="alert"><p>Exactly-once external effects, cross-actor atomic commit, arbitrary-delay proof of read linearizability, durable guest memory, a globally atomic code rollout, built-in workload schedulers, an audit-log retention guarantee, or unlimited availability during partitions.</p></Card></div>
      <p>The diagrams explain the implementation and its intended contract. They do not certify a distributed-systems proof or production readiness. In particular, no-segment calls skip post-upload fencing checks, renewal/fence notification is asynchronous, and the retry window is not an absolute deadline.</p>
    </Section>
  </>;
}

export const pages = { index: Overview, architecture: Architecture, journey: Journey, leases: Leases, durability: Durability, runtime: Runtime, failures: Failures, development: Development, "use-cases": UseCases, patterns: Patterns, reference: Reference };
