//! Typed calls to other actors: `relay` actors call the `counter` example app
//! and each other through clients generated by `statex calls sync`.

use statex_guest::{context, sql, CallError};

mod statex_calls;

wit_bindgen::generate!({
    path: "wit",
    world: "app",
    with: {
        "statex:host/actors@0.1.0": statex_guest::actors,
        "statex:counter/counter": crate::statex_calls::statex::counter::counter,
        "statex:counter/account": crate::statex_calls::statex::counter::account,
        "statex:caller/relay": crate::statex_calls::statex::caller::relay,
    },
});

use exports::example::caller::relay::Guest;
use statex_calls::statex::caller::relay;
use statex_calls::statex::counter::{account, counter};

struct App;

/// Counts a successful call and turns a call error into this method's error.
fn track<T>(r: Result<T, CallError>) -> Result<T, String> {
    let v = r.map_err(|e| e.to_string())?;
    sql::execute("UPDATE stats SET calls = calls + 1 WHERE id = 0", &[]).unwrap();
    Ok(v)
}

impl Guest for App {
    fn bump(key: String, by: i64) -> Result<i64, String> {
        track(counter::increment(&key, by))
    }

    fn enqueue(key: String, by: i64, delay_ms: u64) -> Result<String, String> {
        counter::spawn_after::increment(std::time::Duration::from_millis(delay_ms), &key, by)
            .map_err(|error| error.to_string())
    }

    fn deposit(key: String, amount: u64, memo: Option<String>) -> Result<u64, String> {
        // The outer result is the call, the inner one the callee's own result.
        match track(account::deposit(&key, amount, memo.as_deref()))? {
            Ok(balance) => Ok(balance),
            Err(account::TxError::InvalidAmount) => Err("refused: invalid amount".into()),
            Err(account::TxError::InsufficientFunds(b)) => Err(format!("refused: balance is {b}")),
        }
    }

    fn memos(key: String, limit: u32) -> Result<Vec<String>, String> {
        let entries = track(account::history(&key, limit))?;
        Ok(entries.into_iter().filter_map(|e: account::Entry| e.memo).collect())
    }

    fn ping(path: Vec<String>) -> Result<Vec<String>, String> {
        let mut visited = vec![context::key()];
        if let Some((next, rest)) = path.split_first() {
            visited.extend(track(relay::ping(next, rest))??);
        }
        Ok(visited)
    }

    fn spin(ms: u32) {
        let start = std::time::Instant::now();
        while start.elapsed().as_millis() < u128::from(ms) {
            std::hint::spin_loop();
        }
    }

    fn spin_on(key: String, ms: u32) -> Result<(), String> {
        track(relay::spin(&key, ms))
    }

    fn calls() -> u64 {
        sql::query_scalar::<i64>("SELECT calls FROM stats WHERE id = 0", &[]).unwrap().unwrap_or(0) as u64
    }
}

export!(App);

#[cfg(test)]
mod tests {
    use super::*;
    use statex_guest::testing::{call, try_call};

    /// Stands in for the counter app's `counter` actors.
    struct Counter;
    impl counter::Counter for Counter {
        fn increment(&self, actor: &str, by: i64) -> Result<i64, CallError> {
            match actor {
                "down" => Err(CallError::Unavailable("no owner".into())),
                _ => Ok(by * 10),
            }
        }
    }

    struct Account;
    impl account::Account for Account {
        fn deposit(&self, _: &str, amount: u64, memo: Option<&str>) -> Result<Result<u64, account::TxError>, CallError> {
            Ok(match (amount, memo) {
                (0, _) => Err(account::TxError::InvalidAmount),
                (a, _) => Ok(a + 1),
            })
        }
        fn history(&self, _: &str, _: u32) -> Result<Vec<account::Entry>, CallError> {
            let e = |id, memo: Option<&str>| account::Entry {
                id,
                kind: account::Kind::Deposit,
                amount: 1,
                memo: memo.map(Into::into),
            };
            Ok(vec![e(1, Some("rent")), e(2, None), e(3, Some("pay"))])
        }
    }

    #[test]
    fn typed_calls_with_stubs() {
        counter::stub(Counter);
        account::stub(Account);
        assert_eq!(call("relay", "r", || App::bump("c".into(), 2)), Ok(20));
        assert_eq!(call("relay", "r", || App::deposit("a".into(), 5, Some("x".into()))), Ok(6));
        // Returning Err rolls this relay's transaction back, so this call is not counted.
        assert_eq!(try_call("relay", "r", || App::deposit("a".into(), 0, None)), Err("refused: invalid amount".into()));
        assert_eq!(call("relay", "r", || App::memos("a".into(), 10)), Ok(vec!["rent".into(), "pay".into()]));
        assert_eq!(call("relay", "r", App::calls), 3);
    }

    #[test]
    fn call_errors_roll_back() {
        counter::stub(Counter);
        let r = try_call("relay", "r", || App::bump("down".into(), 1));
        assert_eq!(r, Err("unavailable: no owner".into()));
        assert_eq!(call("relay", "r", App::calls), 0);
    }

    #[test]
    #[should_panic(expected = "without a stub")]
    fn unstubbed_calls_panic() {
        call("relay", "r", || App::spin_on("x".into(), 1)).unwrap();
    }
}
