// Generated by `statex calls sync`. Do not edit.
//! Typed clients of other statex apps' actors.
//!
//! In a component these call the callee through the host. In native
//! `cargo test` they call the stub installed with `<actor type>::stub(..)`
//! (per test thread); a call without a stub panics.
#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

mod bindings_statex_counter {
    wit_bindgen::generate!({
        path: "wit",
        world: "statex:counter/statex-calls",
        with: { "statex:host/actors@0.1.0": statex_guest::actors },
        additional_derives: [PartialEq],
    });
}

mod bindings_statex_caller {
    wit_bindgen::generate!({
        path: "wit",
        world: "statex:caller/statex-calls",
        with: { "statex:host/actors@0.1.0": statex_guest::actors },
        additional_derives: [PartialEq],
    });
}

pub mod statex {
    /// Actors of app `counter`.
    pub mod counter {
        /// A simple counter. Each key (e.g. "alice") is an independent actor.
        pub mod counter {
            use super::super::super::bindings_statex_counter::statex::counter::counter as raw;
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{increment, get, reset, schedule, cancel, alarm_at, fired};

            /// Test double for `counter` actors of app `counter`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Counter {
                fn increment(&self, actor: &str, by: i64) -> Result<i64, statex_guest::actors::CallError> {
                    panic!("counter counter.increment was called without a stub; implement it in the `Counter` stub")
                }
                fn get(&self, actor: &str) -> Result<i64, statex_guest::actors::CallError> {
                    panic!("counter counter.get was called without a stub; implement it in the `Counter` stub")
                }
                fn reset(&self, actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    panic!("counter counter.reset was called without a stub; implement it in the `Counter` stub")
                }
                fn schedule(&self, actor: &str, delay_ms: u64, fail_times: u32) -> Result<(), statex_guest::actors::CallError> {
                    panic!("counter counter.schedule was called without a stub; implement it in the `Counter` stub")
                }
                fn cancel(&self, actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    panic!("counter counter.cancel was called without a stub; implement it in the `Counter` stub")
                }
                fn alarm_at(&self, actor: &str) -> Result<Option<u64>, statex_guest::actors::CallError> {
                    panic!("counter counter.alarm-at was called without a stub; implement it in the `Counter` stub")
                }
                fn fired(&self, actor: &str) -> Result<i64, statex_guest::actors::CallError> {
                    panic!("counter counter.fired was called without a stub; implement it in the `Counter` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Counter>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Counter + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Counter> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("counter counter was called without a stub; call statex_calls::statex::counter::counter::stub(..) first")
                    })
                }

                pub fn increment(actor: &str, by: i64) -> Result<i64, statex_guest::actors::CallError> {
                    current().increment(actor, by)
                }

                pub fn get(actor: &str) -> Result<i64, statex_guest::actors::CallError> {
                    current().get(actor)
                }

                pub fn reset(actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    current().reset(actor)
                }

                pub fn schedule(actor: &str, delay_ms: u64, fail_times: u32) -> Result<(), statex_guest::actors::CallError> {
                    current().schedule(actor, delay_ms, fail_times)
                }

                pub fn cancel(actor: &str) -> Result<(), statex_guest::actors::CallError> {
                    current().cancel(actor)
                }

                pub fn alarm_at(actor: &str) -> Result<Option<u64>, statex_guest::actors::CallError> {
                    current().alarm_at(actor)
                }

                pub fn fired(actor: &str) -> Result<i64, statex_guest::actors::CallError> {
                    current().fired(actor)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, i64) -> Result<i64, statex_guest::actors::CallError> = raw::increment;
                    let _: fn(&str) -> Result<i64, statex_guest::actors::CallError> = raw::get;
                    let _: fn(&str) -> Result<(), statex_guest::actors::CallError> = raw::reset;
                    let _: fn(&str, u64, u32) -> Result<(), statex_guest::actors::CallError> = raw::schedule;
                    let _: fn(&str) -> Result<(), statex_guest::actors::CallError> = raw::cancel;
                    let _: fn(&str) -> Result<Option<u64>, statex_guest::actors::CallError> = raw::alarm_at;
                    let _: fn(&str) -> Result<i64, statex_guest::actors::CallError> = raw::fired;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
        /// A tiny ledger showing records, enums, variants, options and results.
        pub mod account {
            use super::super::super::bindings_statex_counter::statex::counter::account as raw;
            pub use raw::{TxError, Kind, Entry};
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{deposit, withdraw, balance, history};

            /// Test double for `account` actors of app `counter`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Account {
                fn deposit(&self, actor: &str, amount: u64, memo: Option<&str>) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> {
                    panic!("counter account.deposit was called without a stub; implement it in the `Account` stub")
                }
                fn withdraw(&self, actor: &str, amount: u64) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> {
                    panic!("counter account.withdraw was called without a stub; implement it in the `Account` stub")
                }
                fn balance(&self, actor: &str) -> Result<u64, statex_guest::actors::CallError> {
                    panic!("counter account.balance was called without a stub; implement it in the `Account` stub")
                }
                fn history(&self, actor: &str, limit: u32) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    panic!("counter account.history was called without a stub; implement it in the `Account` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Account>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Account + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Account> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("counter account was called without a stub; call statex_calls::statex::counter::account::stub(..) first")
                    })
                }

                pub fn deposit(actor: &str, amount: u64, memo: Option<&str>) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> {
                    current().deposit(actor, amount, memo)
                }

                pub fn withdraw(actor: &str, amount: u64) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> {
                    current().withdraw(actor, amount)
                }

                pub fn balance(actor: &str) -> Result<u64, statex_guest::actors::CallError> {
                    current().balance(actor)
                }

                pub fn history(actor: &str, limit: u32) -> Result<Vec<Entry>, statex_guest::actors::CallError> {
                    current().history(actor, limit)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, u64, Option<&str>) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> = raw::deposit;
                    let _: fn(&str, u64) -> Result<Result<u64, TxError>, statex_guest::actors::CallError> = raw::withdraw;
                    let _: fn(&str) -> Result<u64, statex_guest::actors::CallError> = raw::balance;
                    let _: fn(&str, u32) -> Result<Vec<Entry>, statex_guest::actors::CallError> = raw::history;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
    }
    /// Actors of app `caller`.
    pub mod caller {
        /// Calls actors of the `counter` example app, and other relays.
        pub mod relay {
            use super::super::super::bindings_statex_caller::statex::caller::relay as raw;
            pub use statex_guest::actors::CallError;

            #[cfg(target_arch = "wasm32")]
            pub use raw::{bump, deposit, memos, ping, spin, spin_on, calls};

            /// Test double for `relay` actors of app `caller`; install with [`stub`].
            /// Methods not overridden panic.
            pub trait Relay {
                fn bump(&self, actor: &str, key: &str, by: i64) -> Result<Result<i64, String>, statex_guest::actors::CallError> {
                    panic!("caller relay.bump was called without a stub; implement it in the `Relay` stub")
                }
                fn deposit(&self, actor: &str, key: &str, amount: u64, memo: Option<&str>) -> Result<Result<u64, String>, statex_guest::actors::CallError> {
                    panic!("caller relay.deposit was called without a stub; implement it in the `Relay` stub")
                }
                fn memos(&self, actor: &str, key: &str, limit: u32) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> {
                    panic!("caller relay.memos was called without a stub; implement it in the `Relay` stub")
                }
                fn ping(&self, actor: &str, path: &[String]) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> {
                    panic!("caller relay.ping was called without a stub; implement it in the `Relay` stub")
                }
                fn spin(&self, actor: &str, ms: u32) -> Result<(), statex_guest::actors::CallError> {
                    panic!("caller relay.spin was called without a stub; implement it in the `Relay` stub")
                }
                fn spin_on(&self, actor: &str, key: &str, ms: u32) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    panic!("caller relay.spin-on was called without a stub; implement it in the `Relay` stub")
                }
                fn calls(&self, actor: &str) -> Result<u64, statex_guest::actors::CallError> {
                    panic!("caller relay.calls was called without a stub; implement it in the `Relay` stub")
                }
            }

            #[cfg(not(target_arch = "wasm32"))]
            mod native {
                use super::*;
                use std::{cell::RefCell, rc::Rc};

                thread_local! {
                    static STUB: RefCell<Option<Rc<dyn Relay>>> = RefCell::new(None);
                }

                /// Routes calls on this thread to `s`.
                pub fn stub(s: impl Relay + 'static) {
                    STUB.with(|c| *c.borrow_mut() = Some(Rc::new(s)));
                }

                /// Removes this thread's stub.
                pub fn clear_stub() {
                    STUB.with(|c| *c.borrow_mut() = None);
                }

                fn current() -> Rc<dyn Relay> {
                    STUB.with(|c| c.borrow().clone()).unwrap_or_else(|| {
                        panic!("caller relay was called without a stub; call statex_calls::statex::caller::relay::stub(..) first")
                    })
                }

                pub fn bump(actor: &str, key: &str, by: i64) -> Result<Result<i64, String>, statex_guest::actors::CallError> {
                    current().bump(actor, key, by)
                }

                pub fn deposit(actor: &str, key: &str, amount: u64, memo: Option<&str>) -> Result<Result<u64, String>, statex_guest::actors::CallError> {
                    current().deposit(actor, key, amount, memo)
                }

                pub fn memos(actor: &str, key: &str, limit: u32) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> {
                    current().memos(actor, key, limit)
                }

                pub fn ping(actor: &str, path: &[String]) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> {
                    current().ping(actor, path)
                }

                pub fn spin(actor: &str, ms: u32) -> Result<(), statex_guest::actors::CallError> {
                    current().spin(actor, ms)
                }

                pub fn spin_on(actor: &str, key: &str, ms: u32) -> Result<Result<(), String>, statex_guest::actors::CallError> {
                    current().spin_on(actor, key, ms)
                }

                pub fn calls(actor: &str) -> Result<u64, statex_guest::actors::CallError> {
                    current().calls(actor)
                }

                // Fails to compile if these signatures drift from wit-bindgen's.
                const _: () = {
                    let _: fn(&str, &str, i64) -> Result<Result<i64, String>, statex_guest::actors::CallError> = raw::bump;
                    let _: fn(&str, &str, u64, Option<&str>) -> Result<Result<u64, String>, statex_guest::actors::CallError> = raw::deposit;
                    let _: fn(&str, &str, u32) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> = raw::memos;
                    let _: fn(&str, &[String]) -> Result<Result<Vec<String>, String>, statex_guest::actors::CallError> = raw::ping;
                    let _: fn(&str, u32) -> Result<(), statex_guest::actors::CallError> = raw::spin;
                    let _: fn(&str, &str, u32) -> Result<Result<(), String>, statex_guest::actors::CallError> = raw::spin_on;
                    let _: fn(&str) -> Result<u64, statex_guest::actors::CallError> = raw::calls;
                };
            }

            #[cfg(not(target_arch = "wasm32"))]
            pub use native::*;
        }
    }
}
