# Typed calls to other actors: `relay` actors call the `counter` example app
# (written in Rust) and each other through clients generated by `statex calls sync`.
#
# A call that fails raises statex.Err(call_error) (CallError_Unavailable(...), ...).
# A callee method returning result<T, E> gives back statex.Ok(t) or statex.Err(e).
from typing import List, Optional

from wit_world import exports
from wit_world.imports import account, counter
from wit_world.imports import relay as relays
from wit_world.imports.account import TxError_InsufficientFunds, TxError_InvalidAmount

import statex


def _counted(call, *args):
    """Makes a call; counts it if it succeeded, else fails this method with a readable error."""
    try:
        result = call(*args)
    except statex.Err as e:
        raise statex.Err(statex.describe(e.value))
    statex.execute("UPDATE stats SET calls = calls + 1 WHERE id = 0")
    return result


class Relay(exports.Relay):
    def bump(self, key: str, by: int) -> int:
        return _counted(counter.increment, key, by)

    def deposit(self, key: str, amount: int, memo: Optional[str]) -> int:
        match _counted(account.deposit, key, amount, memo):
            case statex.Ok(balance):
                return balance
            case statex.Err(TxError_InvalidAmount()):
                raise statex.Err("refused: invalid amount")
            case statex.Err(TxError_InsufficientFunds(balance)):
                raise statex.Err("refused: balance is %d" % balance)

    def ping(self, path: List[str]) -> List[str]:
        visited = [statex.key()]
        if path:
            match _counted(relays.ping, path[0], path[1:]):
                case statex.Ok(rest):
                    visited.extend(rest)
                case statex.Err(message):
                    raise statex.Err(message)
        return visited

    def calls(self) -> int:
        return statex.query_scalar("SELECT calls FROM stats WHERE id = 0")
